 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace SevenDSGameS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
		public const Nettention.Proud.RmiID CG_CommonCancel = (Nettention.Proud.RmiID)20000;
		public const Nettention.Proud.RmiID GC_NotifyUserLevelUp = (Nettention.Proud.RmiID)20001;
		public const Nettention.Proud.RmiID CG_FrozenAssetCancel = (Nettention.Proud.RmiID)20002;
		public const Nettention.Proud.RmiID CG_RequestChannelUserInfoOK = (Nettention.Proud.RmiID)20051;
		public const Nettention.Proud.RmiID CG_RequestHeartBeatOK = (Nettention.Proud.RmiID)20052;
		public const Nettention.Proud.RmiID CG_RequestChangeNicknameOK = (Nettention.Proud.RmiID)20053;
		public const Nettention.Proud.RmiID CG_RequestChangeWantToSayOK = (Nettention.Proud.RmiID)20054;
		public const Nettention.Proud.RmiID CG_RequestStageInfoOK = (Nettention.Proud.RmiID)20055;
		public const Nettention.Proud.RmiID CG_RequestTeamInfoOK = (Nettention.Proud.RmiID)20056;
		public const Nettention.Proud.RmiID CG_RequestTeamSlotChangeOK = (Nettention.Proud.RmiID)20057;
		public const Nettention.Proud.RmiID CG_RequestTeamNameChangeOK = (Nettention.Proud.RmiID)20058;
		public const Nettention.Proud.RmiID CG_RequestLobbyInfoOK = (Nettention.Proud.RmiID)20059;
		public const Nettention.Proud.RmiID CG_RequestBasePointInfoOK = (Nettention.Proud.RmiID)20060;
		public const Nettention.Proud.RmiID CG_RequestMercenaryListOK = (Nettention.Proud.RmiID)20061;
		public const Nettention.Proud.RmiID CG_RequestMercenaryInfoOK = (Nettention.Proud.RmiID)20062;
		public const Nettention.Proud.RmiID CG_RequestGuildInfoOK = (Nettention.Proud.RmiID)20063;
		public const Nettention.Proud.RmiID CG_RequestChatStampUpdateBookmarkOK = (Nettention.Proud.RmiID)20064;
		public const Nettention.Proud.RmiID CG_RequestChatStampUpdateQuickMessageOK = (Nettention.Proud.RmiID)20065;
		public const Nettention.Proud.RmiID CG_RequestMainSkinChangeOK = (Nettention.Proud.RmiID)20066;
		public const Nettention.Proud.RmiID CG_RequestEventListOK = (Nettention.Proud.RmiID)20067;
		public const Nettention.Proud.RmiID CG_RequestCheatEnterOK = (Nettention.Proud.RmiID)20068;
		public const Nettention.Proud.RmiID CG_RequestCheatStageClearOK = (Nettention.Proud.RmiID)20069;
		public const Nettention.Proud.RmiID CG_RequestDllGetItemOK = (Nettention.Proud.RmiID)20070;
		public const Nettention.Proud.RmiID CG_RequestRecommendFriendUSNListOK = (Nettention.Proud.RmiID)20071;
		public const Nettention.Proud.RmiID CG_RequestDailyResetOK = (Nettention.Proud.RmiID)20072;
		public const Nettention.Proud.RmiID CG_NotifyMaintenance = (Nettention.Proud.RmiID)20073;
		public const Nettention.Proud.RmiID CG_RequestFrozenAssetRedeemOK = (Nettention.Proud.RmiID)20074;
		public const Nettention.Proud.RmiID CG_RequestSecurityTokenOK = (Nettention.Proud.RmiID)20101;
		public const Nettention.Proud.RmiID CG_RequestNetmarbleAuthOK = (Nettention.Proud.RmiID)20102;
		public const Nettention.Proud.RmiID CG_RequestAuthenticateCreateOK = (Nettention.Proud.RmiID)20103;
		public const Nettention.Proud.RmiID CG_RequestEditorUserInfoByNickNameOK = (Nettention.Proud.RmiID)20104;
		public const Nettention.Proud.RmiID CG_RequestLoginOK = (Nettention.Proud.RmiID)20105;
		public const Nettention.Proud.RmiID CG_RequestLoginInstantlyOK = (Nettention.Proud.RmiID)20106;
		public const Nettention.Proud.RmiID CG_RequestForceLogoutOK = (Nettention.Proud.RmiID)20107;
		public const Nettention.Proud.RmiID CG_RetryRequestOK = (Nettention.Proud.RmiID)20108;
		public const Nettention.Proud.RmiID CG_RequestBillingInitializeOK = (Nettention.Proud.RmiID)20151;
		public const Nettention.Proud.RmiID CG_RequestBillingVerifyPUOK = (Nettention.Proud.RmiID)20152;
		public const Nettention.Proud.RmiID CG_RequestBillingRemainTROK = (Nettention.Proud.RmiID)20153;
		public const Nettention.Proud.RmiID CG_RequestBillingCouponVerifyOK = (Nettention.Proud.RmiID)20154;
		public const Nettention.Proud.RmiID CG_RequestBillingCrossPromotionOK = (Nettention.Proud.RmiID)20155;
		public const Nettention.Proud.RmiID CG_RequestBillingPackageShopOK = (Nettention.Proud.RmiID)20156;
		public const Nettention.Proud.RmiID CG_RequestAgeInputOK = (Nettention.Proud.RmiID)20157;
		public const Nettention.Proud.RmiID CG_Notify_WolverineOK = (Nettention.Proud.RmiID)20158;
		public const Nettention.Proud.RmiID CG_RequestSDKInfoChangeOK = (Nettention.Proud.RmiID)20159;
		public const Nettention.Proud.RmiID CG_RequestSkinLevelUpBySkinMaterialOK = (Nettention.Proud.RmiID)20201;
		public const Nettention.Proud.RmiID CG_RequestSkinResearchOK = (Nettention.Proud.RmiID)20202;
		public const Nettention.Proud.RmiID CG_RequestSkinResearchInitOK = (Nettention.Proud.RmiID)20203;
		public const Nettention.Proud.RmiID CG_RequestSkinMaterialGrindOK = (Nettention.Proud.RmiID)20204;
		public const Nettention.Proud.RmiID CG_RequestSkinAwakenOK = (Nettention.Proud.RmiID)20205;
		public const Nettention.Proud.RmiID CG_RequestSkinHeadStyleChangeOK = (Nettention.Proud.RmiID)20206;
		public const Nettention.Proud.RmiID CG_RequestSkinEvolutionOK = (Nettention.Proud.RmiID)20207;
		public const Nettention.Proud.RmiID CG_RequestSkinSkillLevelUpOK = (Nettention.Proud.RmiID)20208;
		public const Nettention.Proud.RmiID CG_RequestSkinGiveFellowshipExpOK = (Nettention.Proud.RmiID)20209;
		public const Nettention.Proud.RmiID CG_RequestSkinFellowshipLevelUpRewardOK = (Nettention.Proud.RmiID)20210;
		public const Nettention.Proud.RmiID CG_RequestCostumeEquipOK = (Nettention.Proud.RmiID)20211;
		public const Nettention.Proud.RmiID CG_RequestCostumeUnEquipOK = (Nettention.Proud.RmiID)20212;
		public const Nettention.Proud.RmiID CG_RequestCostumeUnLockOK = (Nettention.Proud.RmiID)20213;
		public const Nettention.Proud.RmiID CG_RequestSkinOverEvolutionOK = (Nettention.Proud.RmiID)20214;
		public const Nettention.Proud.RmiID CG_RequestSkinMaxAwakenRewardOK = (Nettention.Proud.RmiID)20215;
		public const Nettention.Proud.RmiID CG_RequestCostumeRegisterOK = (Nettention.Proud.RmiID)20216;
		public const Nettention.Proud.RmiID CG_RequestSkinLoveRewardOK = (Nettention.Proud.RmiID)20217;
		public const Nettention.Proud.RmiID CG_RequestCostumeAutoRegisterOK = (Nettention.Proud.RmiID)20218;
		public const Nettention.Proud.RmiID CG_RequestStoryCostumeOK = (Nettention.Proud.RmiID)20219;
		public const Nettention.Proud.RmiID CG_RequestCostumeLevelUpOK = (Nettention.Proud.RmiID)20220;
		public const Nettention.Proud.RmiID CG_RequestSkinMaxAwakenOK = (Nettention.Proud.RmiID)20221;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquipOK = (Nettention.Proud.RmiID)20251;
		public const Nettention.Proud.RmiID CG_RequestWeaponUnEquipOK = (Nettention.Proud.RmiID)20252;
		public const Nettention.Proud.RmiID CG_RequestWeaponSellOK = (Nettention.Proud.RmiID)20253;
		public const Nettention.Proud.RmiID CG_RequestWeaponGrindOK = (Nettention.Proud.RmiID)20254;
		public const Nettention.Proud.RmiID CG_RequestWeaponUpgradeOK = (Nettention.Proud.RmiID)20255;
		public const Nettention.Proud.RmiID CG_RequestWeaponUpgradeRetryOK = (Nettention.Proud.RmiID)20256;
		public const Nettention.Proud.RmiID CG_RequestWeaponEvolutionOK = (Nettention.Proud.RmiID)20257;
		public const Nettention.Proud.RmiID CG_RequestWeaponEvolutionRetryOK = (Nettention.Proud.RmiID)20258;
		public const Nettention.Proud.RmiID CG_RequestWeaponOptionEnhanceOK = (Nettention.Proud.RmiID)20259;
		public const Nettention.Proud.RmiID CG_RequestWeaponLockOK = (Nettention.Proud.RmiID)20260;
		public const Nettention.Proud.RmiID CG_RequestWeaponUnLockOK = (Nettention.Proud.RmiID)20261;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquipExchangeOK = (Nettention.Proud.RmiID)20262;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquipExchangeAllOK = (Nettention.Proud.RmiID)20263;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquipRecommandOK = (Nettention.Proud.RmiID)20264;
		public const Nettention.Proud.RmiID CG_RequestWeaponCarveOK = (Nettention.Proud.RmiID)20265;
		public const Nettention.Proud.RmiID CG_RequestWeaponCarveRemoveOK = (Nettention.Proud.RmiID)20266;
		public const Nettention.Proud.RmiID CG_RequestStageRejoinOK = (Nettention.Proud.RmiID)20301;
		public const Nettention.Proud.RmiID CG_Request_Main_Stage_StartOK = (Nettention.Proud.RmiID)20302;
		public const Nettention.Proud.RmiID CG_Request_Main_Stage_ClearOK = (Nettention.Proud.RmiID)20303;
		public const Nettention.Proud.RmiID CG_Request_Main_Stage_ContinueOK = (Nettention.Proud.RmiID)20304;
		public const Nettention.Proud.RmiID CG_Request_Free_Stage_StartOK = (Nettention.Proud.RmiID)20305;
		public const Nettention.Proud.RmiID CG_Request_Free_Stage_ClearOK = (Nettention.Proud.RmiID)20306;
		public const Nettention.Proud.RmiID CG_Request_Free_Stage_ContinueOK = (Nettention.Proud.RmiID)20307;
		public const Nettention.Proud.RmiID CG_RequestHawkRunStageStartOK = (Nettention.Proud.RmiID)20308;
		public const Nettention.Proud.RmiID CG_RequestHawkRunStageClearOK = (Nettention.Proud.RmiID)20309;
		public const Nettention.Proud.RmiID CG_RequestEventStageClearOK = (Nettention.Proud.RmiID)20310;
		public const Nettention.Proud.RmiID CG_Request_Quest_Stage_StartOK = (Nettention.Proud.RmiID)20311;
		public const Nettention.Proud.RmiID CG_Request_Quest_Stage_ClearOK = (Nettention.Proud.RmiID)20312;
		public const Nettention.Proud.RmiID CG_Request_Quest_Stage_ContinueOK = (Nettention.Proud.RmiID)20313;
		public const Nettention.Proud.RmiID CG_Request_Week_Stage_StartOK = (Nettention.Proud.RmiID)20314;
		public const Nettention.Proud.RmiID CG_Request_Week_Stage_ClearOK = (Nettention.Proud.RmiID)20315;
		public const Nettention.Proud.RmiID CG_Request_Week_Stage_ContinueOK = (Nettention.Proud.RmiID)20316;
		public const Nettention.Proud.RmiID CG_Request_Boss_Stage_StartOK = (Nettention.Proud.RmiID)20317;
		public const Nettention.Proud.RmiID CG_Request_Boss_Stage_ClearOK = (Nettention.Proud.RmiID)20318;
		public const Nettention.Proud.RmiID CG_Request_Boss_Stage_ContinueOK = (Nettention.Proud.RmiID)20319;
		public const Nettention.Proud.RmiID CG_Request_Memorial_Stage_StartOK = (Nettention.Proud.RmiID)20320;
		public const Nettention.Proud.RmiID CG_Request_Memorial_Stage_ClearOK = (Nettention.Proud.RmiID)20321;
		public const Nettention.Proud.RmiID CG_Request_Memorial_Stage_ContinueOK = (Nettention.Proud.RmiID)20322;
		public const Nettention.Proud.RmiID CG_Request_Limited_Stage_StartOK = (Nettention.Proud.RmiID)20323;
		public const Nettention.Proud.RmiID CG_Request_Limited_Stage_ClearOK = (Nettention.Proud.RmiID)20324;
		public const Nettention.Proud.RmiID CG_Request_Limited_Stage_ContinueOK = (Nettention.Proud.RmiID)20325;
		public const Nettention.Proud.RmiID CG_Request_Main_ExtraStage_StartOK = (Nettention.Proud.RmiID)20326;
		public const Nettention.Proud.RmiID CG_Request_Main_ExtraStage_ClearOK = (Nettention.Proud.RmiID)20327;
		public const Nettention.Proud.RmiID CG_Request_Main_ExtraStage_ContinueOK = (Nettention.Proud.RmiID)20328;
		public const Nettention.Proud.RmiID CG_Request_Boss_ExtraStage_StartOK = (Nettention.Proud.RmiID)20329;
		public const Nettention.Proud.RmiID CG_Request_Boss_ExtraStage_ClearOK = (Nettention.Proud.RmiID)20330;
		public const Nettention.Proud.RmiID CG_Request_Boss_ExtraStage_ContinueOK = (Nettention.Proud.RmiID)20331;
		public const Nettention.Proud.RmiID CG_RequestRewardStageClearOK = (Nettention.Proud.RmiID)20332;
		public const Nettention.Proud.RmiID CG_Request_AnotherMain_Stage_StartOK = (Nettention.Proud.RmiID)20333;
		public const Nettention.Proud.RmiID CG_Request_AnotherMain_Stage_ClearOK = (Nettention.Proud.RmiID)20334;
		public const Nettention.Proud.RmiID CG_Request_AnotherMain_Stage_ContinueOK = (Nettention.Proud.RmiID)20335;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Stage_StartOK = (Nettention.Proud.RmiID)20336;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Stage_ClearOK = (Nettention.Proud.RmiID)20337;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Star_RewardOK = (Nettention.Proud.RmiID)20338;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Group_RewardOK = (Nettention.Proud.RmiID)20339;
		public const Nettention.Proud.RmiID CG_Request_Main_EventAreaStage_StartOK = (Nettention.Proud.RmiID)20351;
		public const Nettention.Proud.RmiID CG_Request_Main_EventAreaStage_ClearOK = (Nettention.Proud.RmiID)20352;
		public const Nettention.Proud.RmiID CG_Request_Main_EventAreaStage_ContinueOK = (Nettention.Proud.RmiID)20353;
		public const Nettention.Proud.RmiID CG_Request_Free_EventAreaStage_StartOK = (Nettention.Proud.RmiID)20354;
		public const Nettention.Proud.RmiID CG_Request_Free_EventAreaStage_ClearOK = (Nettention.Proud.RmiID)20355;
		public const Nettention.Proud.RmiID CG_Request_Free_EventAreaStage_ContinueOK = (Nettention.Proud.RmiID)20356;
		public const Nettention.Proud.RmiID CG_RequestEventAreaRewardStageClearOK = (Nettention.Proud.RmiID)20357;
		public const Nettention.Proud.RmiID CG_Request_Free_EventStage_StartOK = (Nettention.Proud.RmiID)20358;
		public const Nettention.Proud.RmiID CG_Request_Free_EventStage_ClearOK = (Nettention.Proud.RmiID)20359;
		public const Nettention.Proud.RmiID CG_Request_Free_EventStage_ContinueOK = (Nettention.Proud.RmiID)20360;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeOK = (Nettention.Proud.RmiID)20361;
		public const Nettention.Proud.RmiID CG_RequestEventPlayCountRewardOK = (Nettention.Proud.RmiID)20362;
		public const Nettention.Proud.RmiID CG_Request_Main_ListEventStage_StartOK = (Nettention.Proud.RmiID)20363;
		public const Nettention.Proud.RmiID CG_Request_Main_ListEventStage_ClearOK = (Nettention.Proud.RmiID)20364;
		public const Nettention.Proud.RmiID CG_Request_Main_ListEventStage_ContinueOK = (Nettention.Proud.RmiID)20365;
		public const Nettention.Proud.RmiID CG_Request_Free_ListEventStage_StartOK = (Nettention.Proud.RmiID)20366;
		public const Nettention.Proud.RmiID CG_Request_Free_ListEventStage_ClearOK = (Nettention.Proud.RmiID)20367;
		public const Nettention.Proud.RmiID CG_Request_Free_ListEventStage_ContinueOK = (Nettention.Proud.RmiID)20368;
		public const Nettention.Proud.RmiID CG_Request_Main_FinalBossStage_StartOK = (Nettention.Proud.RmiID)20369;
		public const Nettention.Proud.RmiID CG_Request_Main_FinalBossStage_ClearOK = (Nettention.Proud.RmiID)20370;
		public const Nettention.Proud.RmiID CG_Request_Main_FinalBossStage_ContinueOK = (Nettention.Proud.RmiID)20371;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_EventFreeStage_StartOK = (Nettention.Proud.RmiID)20372;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_EventFreeStage_ClearOK = (Nettention.Proud.RmiID)20373;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_EventFreeStage_ContinueOK = (Nettention.Proud.RmiID)20374;
		public const Nettention.Proud.RmiID CG_Request_Limited_EventStage_StartOK = (Nettention.Proud.RmiID)20375;
		public const Nettention.Proud.RmiID CG_Request_Limited_EventStage_ClearOK = (Nettention.Proud.RmiID)20376;
		public const Nettention.Proud.RmiID CG_Request_Limited_EventStage_ContinueOK = (Nettention.Proud.RmiID)20377;
		public const Nettention.Proud.RmiID CG_Request_Boss_EventStage_StartOK = (Nettention.Proud.RmiID)20378;
		public const Nettention.Proud.RmiID CG_Request_Boss_EventStage_ClearOK = (Nettention.Proud.RmiID)20379;
		public const Nettention.Proud.RmiID CG_Request_Boss_EventStage_ContinueOK = (Nettention.Proud.RmiID)20380;
		public const Nettention.Proud.RmiID CG_Request_Monthly_EventStage_StartOK = (Nettention.Proud.RmiID)20381;
		public const Nettention.Proud.RmiID CG_Request_Monthly_EventStage_ClearOK = (Nettention.Proud.RmiID)20382;
		public const Nettention.Proud.RmiID CG_Request_Monthly_EventStage_ContinueOK = (Nettention.Proud.RmiID)20383;
		public const Nettention.Proud.RmiID CG_RequestMonthlyStagePointRewardOK = (Nettention.Proud.RmiID)20384;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_StartOK = (Nettention.Proud.RmiID)20385;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_ClearOK = (Nettention.Proud.RmiID)20386;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_ContinueOK = (Nettention.Proud.RmiID)20387;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_InfoOK = (Nettention.Proud.RmiID)20388;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_Event_Point_RewardOK = (Nettention.Proud.RmiID)20389;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_InfoOK = (Nettention.Proud.RmiID)20390;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_StartOK = (Nettention.Proud.RmiID)20391;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_ClearOK = (Nettention.Proud.RmiID)20392;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_ContinueOK = (Nettention.Proud.RmiID)20393;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_OpenOK = (Nettention.Proud.RmiID)20394;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_RefreshOK = (Nettention.Proud.RmiID)20395;
		public const Nettention.Proud.RmiID CG_RequestWeekStageGaugeRewardOK = (Nettention.Proud.RmiID)20400;
		public const Nettention.Proud.RmiID CG_RequestIngameBattleStartOK = (Nettention.Proud.RmiID)20401;
		public const Nettention.Proud.RmiID CG_RequestStageEndLogOK = (Nettention.Proud.RmiID)20402;
		public const Nettention.Proud.RmiID CG_Request_SingleSiege_ExtraStage_StartOK = (Nettention.Proud.RmiID)20403;
		public const Nettention.Proud.RmiID CG_Request_SingleSiege_ExtraStage_ClearOK = (Nettention.Proud.RmiID)20404;
		public const Nettention.Proud.RmiID CG_Request_SingleSiege_ExtraStage_ContinueOK = (Nettention.Proud.RmiID)20405;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Stage_StartOK = (Nettention.Proud.RmiID)20406;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Stage_ClearOK = (Nettention.Proud.RmiID)20407;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Stage_ContinueOK = (Nettention.Proud.RmiID)20408;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Season_InfoOK = (Nettention.Proud.RmiID)20409;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Season_Rank_InfoOK = (Nettention.Proud.RmiID)20410;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Stage_StartOK = (Nettention.Proud.RmiID)20420;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Stage_ClearOK = (Nettention.Proud.RmiID)20421;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Lobby_InfoOK = (Nettention.Proud.RmiID)20422;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Rank_InfoOK = (Nettention.Proud.RmiID)20423;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_LastWeek_Rank_InfoOK = (Nettention.Proud.RmiID)20424;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Time_RefreshOK = (Nettention.Proud.RmiID)20425;
		public const Nettention.Proud.RmiID CG_RequestMailListOK = (Nettention.Proud.RmiID)20501;
		public const Nettention.Proud.RmiID CG_RequestMailConfirmOK = (Nettention.Proud.RmiID)20502;
		public const Nettention.Proud.RmiID CG_RequestMailConfirmAllOK = (Nettention.Proud.RmiID)20503;
		public const Nettention.Proud.RmiID CG_RequestMailHistoryListOK = (Nettention.Proud.RmiID)20504;
		public const Nettention.Proud.RmiID CG_RequestMailRecentlyHistoryListOK = (Nettention.Proud.RmiID)20505;
		public const Nettention.Proud.RmiID CG_RequestFriendMailListOK = (Nettention.Proud.RmiID)20506;
		public const Nettention.Proud.RmiID CG_RequestFriendMailConfirmOK = (Nettention.Proud.RmiID)20507;
		public const Nettention.Proud.RmiID CG_RequestFriendMailConfirmAllOK = (Nettention.Proud.RmiID)20508;
		public const Nettention.Proud.RmiID CG_RequestNoticeMailRewardOK = (Nettention.Proud.RmiID)20509;
		public const Nettention.Proud.RmiID CG_RequestPackageMailListOK = (Nettention.Proud.RmiID)20510;
		public const Nettention.Proud.RmiID CG_RequestPackageMailGetOK = (Nettention.Proud.RmiID)20511;
		public const Nettention.Proud.RmiID CG_RequestPackageMailHistoryListOK = (Nettention.Proud.RmiID)20512;
		public const Nettention.Proud.RmiID CG_RequestLevelUpPackageRewardOK = (Nettention.Proud.RmiID)20513;
		public const Nettention.Proud.RmiID CG_RequestLevelUpPackageRewardAllOK = (Nettention.Proud.RmiID)20514;
		public const Nettention.Proud.RmiID CG_RequestAttendancePackageRewardOK = (Nettention.Proud.RmiID)20515;
		public const Nettention.Proud.RmiID CG_RequestAttendancePackageRewardAllOK = (Nettention.Proud.RmiID)20516;
		public const Nettention.Proud.RmiID CG_RequestMailADRewardOK = (Nettention.Proud.RmiID)20517;
		public const Nettention.Proud.RmiID CG_RequestItemInventoryBuyOK = (Nettention.Proud.RmiID)20551;
		public const Nettention.Proud.RmiID CG_RequestWeaponInventoryBuyOK = (Nettention.Proud.RmiID)20552;
		public const Nettention.Proud.RmiID CG_RequestWeekStageKeyBuyOK = (Nettention.Proud.RmiID)20553;
		public const Nettention.Proud.RmiID CG_RequestDiaShopInfoOK = (Nettention.Proud.RmiID)20554;
		public const Nettention.Proud.RmiID CG_RequestDiaShopBuyOK = (Nettention.Proud.RmiID)20555;
		public const Nettention.Proud.RmiID CG_RequestGambleShopBuyOK = (Nettention.Proud.RmiID)20556;
		public const Nettention.Proud.RmiID CG_RequestItemGambleShopInfoOK = (Nettention.Proud.RmiID)20557;
		public const Nettention.Proud.RmiID CG_RequestItemGambleShopBuyOK = (Nettention.Proud.RmiID)20558;
		public const Nettention.Proud.RmiID CG_RequestRandomShopBuyOK = (Nettention.Proud.RmiID)20559;
		public const Nettention.Proud.RmiID CG_RequestRandomShopRefreshOK = (Nettention.Proud.RmiID)20560;
		public const Nettention.Proud.RmiID CG_RequestRandomShopInfoOK = (Nettention.Proud.RmiID)20561;
		public const Nettention.Proud.RmiID CG_RequestBasePointShopInfoOK = (Nettention.Proud.RmiID)20562;
		public const Nettention.Proud.RmiID CG_RequestBasePointShopBuyOK = (Nettention.Proud.RmiID)20563;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpShopInfoOK = (Nettention.Proud.RmiID)20564;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpShopBuyOK = (Nettention.Proud.RmiID)20565;
		public const Nettention.Proud.RmiID CG_RequestCoinShopInfoOK = (Nettention.Proud.RmiID)20566;
		public const Nettention.Proud.RmiID CG_RequestCoinShopBuyOK = (Nettention.Proud.RmiID)20567;
		public const Nettention.Proud.RmiID CG_RequestCoinShopDailyBuyOK = (Nettention.Proud.RmiID)20568;
		public const Nettention.Proud.RmiID CG_RequestCostumeShopInfoOK = (Nettention.Proud.RmiID)20569;
		public const Nettention.Proud.RmiID CG_RequestCostumeShopBuyOK = (Nettention.Proud.RmiID)20570;
		public const Nettention.Proud.RmiID CG_RequestFriendPointShopInfoOK = (Nettention.Proud.RmiID)20571;
		public const Nettention.Proud.RmiID CG_RequestFriendPointShopBuyOK = (Nettention.Proud.RmiID)20572;
		public const Nettention.Proud.RmiID CG_RequestCommonItemSellOK = (Nettention.Proud.RmiID)20573;
		public const Nettention.Proud.RmiID CG_RequestCommonItemRemoveOK = (Nettention.Proud.RmiID)20574;
		public const Nettention.Proud.RmiID CG_RequestPackageShopInfoOK = (Nettention.Proud.RmiID)20575;
		public const Nettention.Proud.RmiID CG_RequestGambleShopInfoOK = (Nettention.Proud.RmiID)20579;
		public const Nettention.Proud.RmiID CG_RequestADRouletteRewardOK = (Nettention.Proud.RmiID)20578;
		public const Nettention.Proud.RmiID CG_RequestRandomShopVisitRewardOK = (Nettention.Proud.RmiID)20576;
		public const Nettention.Proud.RmiID CG_RequestRandomShopScheduleInfoOK = (Nettention.Proud.RmiID)20577;
		public const Nettention.Proud.RmiID CG_RequestPackageBuyOK = (Nettention.Proud.RmiID)20601;
		public const Nettention.Proud.RmiID CG_RequestBuyDiaOK = (Nettention.Proud.RmiID)20602;
		public const Nettention.Proud.RmiID CG_RequestBuyGoldOK = (Nettention.Proud.RmiID)20603;
		public const Nettention.Proud.RmiID CG_RequestBuyStaminaOK = (Nettention.Proud.RmiID)20604;
		public const Nettention.Proud.RmiID CG_RequestGuildShopInfoOK = (Nettention.Proud.RmiID)20605;
		public const Nettention.Proud.RmiID CG_RequestGuildShopBuyOK = (Nettention.Proud.RmiID)20606;
		public const Nettention.Proud.RmiID CG_RequestBasePointShopResetOK = (Nettention.Proud.RmiID)20607;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpShopResetOK = (Nettention.Proud.RmiID)20608;
		public const Nettention.Proud.RmiID CG_RequestCostumeShopPackageBuyOK = (Nettention.Proud.RmiID)20609;
		public const Nettention.Proud.RmiID CG_RequestFinalBossShopInfoOK = (Nettention.Proud.RmiID)20610;
		public const Nettention.Proud.RmiID CG_RequestFinalBossShopBuyOK = (Nettention.Proud.RmiID)20611;
		public const Nettention.Proud.RmiID CG_RequestEventCollaborationCoinShopInfoOK = (Nettention.Proud.RmiID)20612;
		public const Nettention.Proud.RmiID CG_RequestEventCollaborationCoinShopBuyOK = (Nettention.Proud.RmiID)20613;
		public const Nettention.Proud.RmiID CG_RequestGuildShopResetOK = (Nettention.Proud.RmiID)20614;
		public const Nettention.Proud.RmiID CG_RequestCoinShopOnceBuyOK = (Nettention.Proud.RmiID)20615;
		public const Nettention.Proud.RmiID CG_RequestBingoGambleShopInfoOK = (Nettention.Proud.RmiID)20616;
		public const Nettention.Proud.RmiID CG_RequestBingoGambleShopResetOK = (Nettention.Proud.RmiID)20617;
		public const Nettention.Proud.RmiID CG_RequestBingoGambleShopRewardOK = (Nettention.Proud.RmiID)20618;
		public const Nettention.Proud.RmiID CG_RequestDiaShopPackageBuyOK = (Nettention.Proud.RmiID)20620;
		public const Nettention.Proud.RmiID CG_RequestGambleChoiceShopBuyOK = (Nettention.Proud.RmiID)20621;
		public const Nettention.Proud.RmiID CG_RequestFreePackageRewardOK = (Nettention.Proud.RmiID)20622;
		public const Nettention.Proud.RmiID CG_RequestPackageMissionCloseOK = (Nettention.Proud.RmiID)20623;
		public const Nettention.Proud.RmiID CG_RequestMissionProgressOK = (Nettention.Proud.RmiID)20651;
		public const Nettention.Proud.RmiID CG_RequestMissionClearOK = (Nettention.Proud.RmiID)20652;
		public const Nettention.Proud.RmiID CG_RequestMissionEventClearOK = (Nettention.Proud.RmiID)20653;
		public const Nettention.Proud.RmiID CG_RequestMissionGetAchievePointRewardOK = (Nettention.Proud.RmiID)20654;
		public const Nettention.Proud.RmiID CG_RequestQuestStartOK = (Nettention.Proud.RmiID)20701;
		public const Nettention.Proud.RmiID CG_RequestQuestProgressOK = (Nettention.Proud.RmiID)20702;
		public const Nettention.Proud.RmiID CG_RequestQuestClearOK = (Nettention.Proud.RmiID)20703;
		public const Nettention.Proud.RmiID CG_RequestQuestRemoveOK = (Nettention.Proud.RmiID)20704;
		public const Nettention.Proud.RmiID CG_RequestNetmarbleQuestAchieveOK = (Nettention.Proud.RmiID)20705;
		public const Nettention.Proud.RmiID CG_RequestNetmarbleQuestRewardOK = (Nettention.Proud.RmiID)20706;
		public const Nettention.Proud.RmiID CG_RequestDirectSelectorRewardOK = (Nettention.Proud.RmiID)20707;
		public const Nettention.Proud.RmiID CG_RequestQuestChapterClearOK = (Nettention.Proud.RmiID)20708;
		public const Nettention.Proud.RmiID CG_RequestEventQuestClearOK = (Nettention.Proud.RmiID)20709;
		public const Nettention.Proud.RmiID CG_RequestAnotherQuestClearOK = (Nettention.Proud.RmiID)20710;
		public const Nettention.Proud.RmiID CG_RequestQuestGuideListAllClearRewardOK = (Nettention.Proud.RmiID)20711;
		public const Nettention.Proud.RmiID CG_RequestLobbyVRSearchOK = (Nettention.Proud.RmiID)20751;
		public const Nettention.Proud.RmiID CG_RequestLobbyVRHelbramOK = (Nettention.Proud.RmiID)20752;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcSkinOK = (Nettention.Proud.RmiID)20753;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcGiftOK = (Nettention.Proud.RmiID)20754;
		public const Nettention.Proud.RmiID CG_RequestLobbyKingAmberOK = (Nettention.Proud.RmiID)20755;
		public const Nettention.Proud.RmiID CG_RequestLobbyDropInteractiveOpenOK = (Nettention.Proud.RmiID)20756;
		public const Nettention.Proud.RmiID CG_RequestLobbyUniqueInteractiveOpenOK = (Nettention.Proud.RmiID)20757;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcTalkInfoOK = (Nettention.Proud.RmiID)20758;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcTalkChoiceOK = (Nettention.Proud.RmiID)20759;
		public const Nettention.Proud.RmiID CG_RequestLobbyBarrelOK = (Nettention.Proud.RmiID)20760;
		public const Nettention.Proud.RmiID CG_RequestLobbyBarrelRefillOK = (Nettention.Proud.RmiID)20761;
		public const Nettention.Proud.RmiID CG_RequestLobbyCleanTableOK = (Nettention.Proud.RmiID)20762;
		public const Nettention.Proud.RmiID CG_RequestLobbyServeBeerOK = (Nettention.Proud.RmiID)20763;
		public const Nettention.Proud.RmiID CG_RequestLobbyPlayJukeboxOK = (Nettention.Proud.RmiID)20764;
		public const Nettention.Proud.RmiID CG_RequestLobbyElizabethTouchOK = (Nettention.Proud.RmiID)20765;
		public const Nettention.Proud.RmiID CG_RequestLobbyHawkAngerOK = (Nettention.Proud.RmiID)20766;
		public const Nettention.Proud.RmiID CG_RequestAttendanceRewardOK = (Nettention.Proud.RmiID)20767;
		public const Nettention.Proud.RmiID CG_RequestAttendanceEventRewardOK = (Nettention.Proud.RmiID)20768;
		public const Nettention.Proud.RmiID CG_RequestCookingStartOK = (Nettention.Proud.RmiID)20769;
		public const Nettention.Proud.RmiID CG_RequestRecipeActiveOK = (Nettention.Proud.RmiID)20770;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeOrderInfoOK = (Nettention.Proud.RmiID)20771;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeOrderOK = (Nettention.Proud.RmiID)20772;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeDisorderOK = (Nettention.Proud.RmiID)20773;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeCollectOK = (Nettention.Proud.RmiID)20774;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeCollectOneSlotOK = (Nettention.Proud.RmiID)20775;
		public const Nettention.Proud.RmiID CG_RequestCookingUseCookingBuffOK = (Nettention.Proud.RmiID)20776;
		public const Nettention.Proud.RmiID CG_RequestGuestInfoOK = (Nettention.Proud.RmiID)20777;
		public const Nettention.Proud.RmiID CG_RequestGuestChangeOK = (Nettention.Proud.RmiID)20778;
		public const Nettention.Proud.RmiID CG_RequestGuestChangeTargetOK = (Nettention.Proud.RmiID)20779;
		public const Nettention.Proud.RmiID CG_RequestGuestTalkOK = (Nettention.Proud.RmiID)20780;
		public const Nettention.Proud.RmiID CG_RequestGuestGiftOK = (Nettention.Proud.RmiID)20781;
		public const Nettention.Proud.RmiID CG_RequestBirthdayNpcInfoOK = (Nettention.Proud.RmiID)20782;
		public const Nettention.Proud.RmiID CG_RequestRestRewardOK = (Nettention.Proud.RmiID)20783;
		public const Nettention.Proud.RmiID CG_RequestAttendanceFortuneEventRewardOK = (Nettention.Proud.RmiID)20784;
		public const Nettention.Proud.RmiID CG_RequestBasePointGoldDonationOK = (Nettention.Proud.RmiID)20801;
		public const Nettention.Proud.RmiID CG_RequestBasePointSetTriggerOK = (Nettention.Proud.RmiID)20802;
		public const Nettention.Proud.RmiID CG_RequestBasePointDropInteractiveOpenOK = (Nettention.Proud.RmiID)20803;
		public const Nettention.Proud.RmiID CG_RequestBasePointUniqueInteractiveOpenOK = (Nettention.Proud.RmiID)20804;
		public const Nettention.Proud.RmiID CG_RequestBasePointDailyRewardOK = (Nettention.Proud.RmiID)20805;
		public const Nettention.Proud.RmiID CG_RequestBasePointDonationEventRewardOK = (Nettention.Proud.RmiID)20806;
		public const Nettention.Proud.RmiID CG_RequestBasePointDonationInfoOK = (Nettention.Proud.RmiID)20807;
		public const Nettention.Proud.RmiID CG_RequestBasePointEventGoldDonationOK = (Nettention.Proud.RmiID)20808;
		public const Nettention.Proud.RmiID CG_RequestEventBasepointInfoOK = (Nettention.Proud.RmiID)20809;
		public const Nettention.Proud.RmiID GC_NotifyDestroyInvite = (Nettention.Proud.RmiID)20851;
		public const Nettention.Proud.RmiID CG_RequestDestroySetInviteOptionOK = (Nettention.Proud.RmiID)20852;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetUserLoginListOK = (Nettention.Proud.RmiID)20853;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetFriendLoginListOK = (Nettention.Proud.RmiID)20854;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetGuildLoginListOK = (Nettention.Proud.RmiID)20855;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetReceivedInvitationListOK = (Nettention.Proud.RmiID)20856;
		public const Nettention.Proud.RmiID CG_RequestDestroyInviteOK = (Nettention.Proud.RmiID)20857;
		public const Nettention.Proud.RmiID CG_RequestDestroyRemoveInvitationOK = (Nettention.Proud.RmiID)20858;
		public const Nettention.Proud.RmiID CG_RequestDestroyRemoveJoinInfoOK = (Nettention.Proud.RmiID)20859;
		public const Nettention.Proud.RmiID CG_RequestDestroyCreateOK = (Nettention.Proud.RmiID)20860;
		public const Nettention.Proud.RmiID CG_RequestDestroyStartOK = (Nettention.Proud.RmiID)20861;
		public const Nettention.Proud.RmiID CG_RequestDestroyBattleStartOK = (Nettention.Proud.RmiID)20862;
		public const Nettention.Proud.RmiID CG_RequestDestroyJoinOK = (Nettention.Proud.RmiID)20863;
		public const Nettention.Proud.RmiID CG_RequestDestroyClearOK = (Nettention.Proud.RmiID)20864;
		public const Nettention.Proud.RmiID CG_RequestDestroyReJoinOK = (Nettention.Proud.RmiID)20865;
		public const Nettention.Proud.RmiID CG_RequestDestroyRemoveOK = (Nettention.Proud.RmiID)20866;
		public const Nettention.Proud.RmiID CG_RequestDestroyBattleEndOK = (Nettention.Proud.RmiID)20867;
		public const Nettention.Proud.RmiID CG_RequestDestroyInviteAIOK = (Nettention.Proud.RmiID)20868;
		public const Nettention.Proud.RmiID CG_RequestDestroyKickOutAIOK = (Nettention.Proud.RmiID)20869;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyCreateOK = (Nettention.Proud.RmiID)20870;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyClearOK = (Nettention.Proud.RmiID)20871;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyStartOK = (Nettention.Proud.RmiID)20872;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyRemoveOK = (Nettention.Proud.RmiID)20873;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyCreateOK = (Nettention.Proud.RmiID)20874;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyStartOK = (Nettention.Proud.RmiID)20875;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyClearOK = (Nettention.Proud.RmiID)20876;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyPointRefreshOK = (Nettention.Proud.RmiID)20877;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyUserRewardOK = (Nettention.Proud.RmiID)20878;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyWorldRewardOK = (Nettention.Proud.RmiID)20879;
		public const Nettention.Proud.RmiID CG_RequestFriendListOK = (Nettention.Proud.RmiID)20901;
		public const Nettention.Proud.RmiID CG_RequestFriendGuildInfoOK = (Nettention.Proud.RmiID)20902;
		public const Nettention.Proud.RmiID CG_RequestFriendApplySendListOK = (Nettention.Proud.RmiID)20903;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveListOK = (Nettention.Proud.RmiID)20904;
		public const Nettention.Proud.RmiID CG_RequestFriendApplySendOK = (Nettention.Proud.RmiID)20905;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyRejectOK = (Nettention.Proud.RmiID)20906;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveAcceptOK = (Nettention.Proud.RmiID)20907;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveAcceptListOK = (Nettention.Proud.RmiID)20908;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveRefuseOK = (Nettention.Proud.RmiID)20909;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveRefuseListOK = (Nettention.Proud.RmiID)20910;
		public const Nettention.Proud.RmiID CG_RequestFriendRemoveOK = (Nettention.Proud.RmiID)20911;
		public const Nettention.Proud.RmiID CG_RequestFriendSearchOK = (Nettention.Proud.RmiID)20912;
		public const Nettention.Proud.RmiID CG_RequestFriendVisitOK = (Nettention.Proud.RmiID)20913;
		public const Nettention.Proud.RmiID CG_RequestFriendPointSendOK = (Nettention.Proud.RmiID)20914;
		public const Nettention.Proud.RmiID CG_RequestFriendPointSendAllOK = (Nettention.Proud.RmiID)20915;
		public const Nettention.Proud.RmiID CG_RequestFriendLobbyInfoOK = (Nettention.Proud.RmiID)20916;
		public const Nettention.Proud.RmiID CG_RequestFriendCookingRecipeInfoOK = (Nettention.Proud.RmiID)20917;
		public const Nettention.Proud.RmiID CG_RequestFriendCookingEatOK = (Nettention.Proud.RmiID)20918;
		public const Nettention.Proud.RmiID CG_RequestFriendCookingEatFriendListOK = (Nettention.Proud.RmiID)20919;
		public const Nettention.Proud.RmiID CG_RequestGuildRecommendListOK = (Nettention.Proud.RmiID)20951;
		public const Nettention.Proud.RmiID CG_RequestGuildInfoWithMemberListOK = (Nettention.Proud.RmiID)20952;
		public const Nettention.Proud.RmiID CG_RequestGuildSearchByNameOK = (Nettention.Proud.RmiID)20953;
		public const Nettention.Proud.RmiID CG_RequestGuildCreateOK = (Nettention.Proud.RmiID)20954;
		public const Nettention.Proud.RmiID CG_RequestGuildDisbandOK = (Nettention.Proud.RmiID)20955;
		public const Nettention.Proud.RmiID CG_RequestGuildApplicantListOK = (Nettention.Proud.RmiID)20956;
		public const Nettention.Proud.RmiID CG_RequestGuildApplyOK = (Nettention.Proud.RmiID)20957;
		public const Nettention.Proud.RmiID CG_RequestGuildReturnApplicationOK = (Nettention.Proud.RmiID)20958;
		public const Nettention.Proud.RmiID CG_RequestGuildAcceptApplicantOK = (Nettention.Proud.RmiID)20959;
		public const Nettention.Proud.RmiID CG_RequestGuildRejectApplicantOK = (Nettention.Proud.RmiID)20960;
		public const Nettention.Proud.RmiID CG_RequestGuildLevelUpOK = (Nettention.Proud.RmiID)20961;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeNameOK = (Nettention.Proud.RmiID)20962;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeBoardOK = (Nettention.Proud.RmiID)20963;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeMasterOK = (Nettention.Proud.RmiID)20964;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeMemberGradeOK = (Nettention.Proud.RmiID)20965;
		public const Nettention.Proud.RmiID CG_RequestGuildKickOutMemberOK = (Nettention.Proud.RmiID)20966;
		public const Nettention.Proud.RmiID CG_RequestGuildLeaveOK = (Nettention.Proud.RmiID)20967;
		public const Nettention.Proud.RmiID CG_RequestGuildRoomInfoOK = (Nettention.Proud.RmiID)20968;
		public const Nettention.Proud.RmiID CG_RequestGuildAttendanceOK = (Nettention.Proud.RmiID)20969;
		public const Nettention.Proud.RmiID CG_RequestGuildAttendanceRewardOK = (Nettention.Proud.RmiID)20970;
		public const Nettention.Proud.RmiID CG_RequestGuildUserInfoOK = (Nettention.Proud.RmiID)20971;
		public const Nettention.Proud.RmiID CG_RequestGuildAttendanceStatusOK = (Nettention.Proud.RmiID)20972;
		public const Nettention.Proud.RmiID GC_NotifyGuildKickout = (Nettention.Proud.RmiID)20973;
		public const Nettention.Proud.RmiID CG_RequestGuildDonationOK = (Nettention.Proud.RmiID)20974;
		public const Nettention.Proud.RmiID CG_RequestGuildDonationInitializeOK = (Nettention.Proud.RmiID)20975;
		public const Nettention.Proud.RmiID CG_RequestGuildMissionInfoOK = (Nettention.Proud.RmiID)20976;
		public const Nettention.Proud.RmiID CG_RequestGuildMissionRewardOK = (Nettention.Proud.RmiID)20977;
		public const Nettention.Proud.RmiID GC_NotifyGuildAcceptApplicantOK = (Nettention.Proud.RmiID)20978;
		public const Nettention.Proud.RmiID CG_RequestGuildDonationInfoOK = (Nettention.Proud.RmiID)20979;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillInfoOK = (Nettention.Proud.RmiID)20980;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillLevelUpOK = (Nettention.Proud.RmiID)20981;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillUseOK = (Nettention.Proud.RmiID)20982;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillDisuseOK = (Nettention.Proud.RmiID)20983;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillUseInfoOK = (Nettention.Proud.RmiID)20984;
		public const Nettention.Proud.RmiID CG_RequestGuildMemberRankPointRewardOK = (Nettention.Proud.RmiID)20985;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointRegisterOK = (Nettention.Proud.RmiID)20986;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointMemeberRankListOK = (Nettention.Proud.RmiID)20987;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointGuildRankListOK = (Nettention.Proud.RmiID)20988;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointUserRankListOK = (Nettention.Proud.RmiID)20989;
		public const Nettention.Proud.RmiID CG_RequestAPRechargeByUseItemOK = (Nettention.Proud.RmiID)21001;
		public const Nettention.Proud.RmiID CG_RequestWeekStageKeyOpenOK = (Nettention.Proud.RmiID)21002;
		public const Nettention.Proud.RmiID CG_RequestFoodBuffAutoUseOnOffOK = (Nettention.Proud.RmiID)21003;
		public const Nettention.Proud.RmiID CG_RequestItemUseRankExpOK = (Nettention.Proud.RmiID)21004;
		public const Nettention.Proud.RmiID CG_RequestItemUseBoxOpenOK = (Nettention.Proud.RmiID)21005;
		public const Nettention.Proud.RmiID CG_RequestItemUseRecipeExpOK = (Nettention.Proud.RmiID)21006;
		public const Nettention.Proud.RmiID CG_RequestItemUseWeeklyKeyBoxOK = (Nettention.Proud.RmiID)21007;
		public const Nettention.Proud.RmiID CG_RequestItemUseWeaponTicketOK = (Nettention.Proud.RmiID)21008;
		public const Nettention.Proud.RmiID CG_RequestItemUseMusicOK = (Nettention.Proud.RmiID)21009;
		public const Nettention.Proud.RmiID CG_RequestTutorialAddStepOK = (Nettention.Proud.RmiID)21011;
		public const Nettention.Proud.RmiID CG_RequestTutorialSetFlagOK = (Nettention.Proud.RmiID)21012;
		public const Nettention.Proud.RmiID CG_RequestTutorialHeroFlagOK = (Nettention.Proud.RmiID)21013;
		public const Nettention.Proud.RmiID CG_RequestTutorialGambleShopBuyOK = (Nettention.Proud.RmiID)21014;
		public const Nettention.Proud.RmiID CG_RequestBattleTutorialInfoOK = (Nettention.Proud.RmiID)21015;
		public const Nettention.Proud.RmiID CG_RequestBattleTutorialSetOK = (Nettention.Proud.RmiID)21016;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchCreateOK = (Nettention.Proud.RmiID)21021;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchFriendListOK = (Nettention.Proud.RmiID)21022;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchInviteOK = (Nettention.Proud.RmiID)21023;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchReceivedInviteListOK = (Nettention.Proud.RmiID)21024;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchInviteAcceptOK = (Nettention.Proud.RmiID)21025;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchInviteRejectOK = (Nettention.Proud.RmiID)21026;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchStartOK = (Nettention.Proud.RmiID)21027;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchBattleStartOK = (Nettention.Proud.RmiID)21028;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchClearOK = (Nettention.Proud.RmiID)21029;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchExitOK = (Nettention.Proud.RmiID)21030;
		public const Nettention.Proud.RmiID GC_NotifyFriendlyMatchInvite = (Nettention.Proud.RmiID)21031;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchSetInviteOptionOK = (Nettention.Proud.RmiID)21032;
		public const Nettention.Proud.RmiID CG_RequestEventMissionGetAchievePointRewardOK = (Nettention.Proud.RmiID)21051;
		public const Nettention.Proud.RmiID CG_RequestEventMissionCompleteRewardOK = (Nettention.Proud.RmiID)21052;
		public const Nettention.Proud.RmiID CG_RequestEventMissionInfoOk = (Nettention.Proud.RmiID)21053;
		public const Nettention.Proud.RmiID CG_RequestLobbyHousingShopInfoOK = (Nettention.Proud.RmiID)21061;
		public const Nettention.Proud.RmiID CG_RequestLobbyHousingShopBuyOK = (Nettention.Proud.RmiID)21062;
		public const Nettention.Proud.RmiID CG_RequestLobbyFurnitureRegistOK = (Nettention.Proud.RmiID)21063;
		public const Nettention.Proud.RmiID CG_RequestUserMusicEditOK = (Nettention.Proud.RmiID)21064;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassInfoOK = (Nettention.Proud.RmiID)21071;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassRankUpRewardOK = (Nettention.Proud.RmiID)21072;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassRankUpRewardAllOK = (Nettention.Proud.RmiID)21073;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassRankBuyOK = (Nettention.Proud.RmiID)21074;
		public const Nettention.Proud.RmiID CG_RequestStepupGambleShopBuyOK = (Nettention.Proud.RmiID)21081;
		public const Nettention.Proud.RmiID CG_RequestStepupGambleMileageRewardOK = (Nettention.Proud.RmiID)21082;
		public const Nettention.Proud.RmiID CG_RequestWestSideServerInfo_RandomOK = (Nettention.Proud.RmiID)21091;
		public const Nettention.Proud.RmiID CG_RequestWestSideServerInfo_FixedOK = (Nettention.Proud.RmiID)21092;
		public const Nettention.Proud.RmiID CG_RequestWestSideServerInfo_RecommandOK = (Nettention.Proud.RmiID)21093;
		public const Nettention.Proud.RmiID CG_RequestWestSide_PlayerInfoOK = (Nettention.Proud.RmiID)21094;
		public const Nettention.Proud.RmiID CG_RequestWestSide_PlayerteamInfoOK = (Nettention.Proud.RmiID)21095;
		public const Nettention.Proud.RmiID CG_RequestWestSide_PlayerGuildInfoOK = (Nettention.Proud.RmiID)21096;
		public const Nettention.Proud.RmiID CG_RequestWorldChattingChannelOK = (Nettention.Proud.RmiID)21097;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLobbyInfoOK = (Nettention.Proud.RmiID)21101;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpJoinOK = (Nettention.Proud.RmiID)21102;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpTopRankerListOK = (Nettention.Proud.RmiID)21103;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLastRankerListOK = (Nettention.Proud.RmiID)21104;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpMatchingOK = (Nettention.Proud.RmiID)21105;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpBattleStartOK = (Nettention.Proud.RmiID)21106;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpBattleEndOK = (Nettention.Proud.RmiID)21107;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpRollbackOK = (Nettention.Proud.RmiID)21108;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpIngameBattleStartOK = (Nettention.Proud.RmiID)21109;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerLobbyInfoOK = (Nettention.Proud.RmiID)21111;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerJoinOK = (Nettention.Proud.RmiID)21112;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerTopRankerListOK = (Nettention.Proud.RmiID)21113;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerMatchingOK = (Nettention.Proud.RmiID)21114;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerBattleStartOK = (Nettention.Proud.RmiID)21115;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerBattleEndOK = (Nettention.Proud.RmiID)21116;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpAllInfoOK = (Nettention.Proud.RmiID)21117;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLastRankerBattleInfoOK = (Nettention.Proud.RmiID)21118;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLastRankerBattleStartOK = (Nettention.Proud.RmiID)21119;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerRollbackOK = (Nettention.Proud.RmiID)21120;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerIngameBattleStartOK = (Nettention.Proud.RmiID)21121;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionLobbyInfoOK = (Nettention.Proud.RmiID)21131;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionJoinOK = (Nettention.Proud.RmiID)21132;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionTopRankerListOK = (Nettention.Proud.RmiID)21133;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionMatchingOK = (Nettention.Proud.RmiID)21134;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionBattleStartOK = (Nettention.Proud.RmiID)21135;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionBattleEndOK = (Nettention.Proud.RmiID)21136;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionIngameBattleStartOK = (Nettention.Proud.RmiID)21137;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionHistoryOK = (Nettention.Proud.RmiID)21138;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionChangeMatchingListOK = (Nettention.Proud.RmiID)21139;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionMatchingSimpleInfoOK = (Nettention.Proud.RmiID)21140;
		public const Nettention.Proud.RmiID CG_RequestPvpSeasonInfoOK = (Nettention.Proud.RmiID)21141;
		public const Nettention.Proud.RmiID CG_RequestPvpSeasonHistoryOK = (Nettention.Proud.RmiID)21142;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeInfoOK = (Nettention.Proud.RmiID)21151;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeBoxGachaInfoOK = (Nettention.Proud.RmiID)21152;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeBoxGachaPickupOK = (Nettention.Proud.RmiID)21153;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeBoxGachaResetOK = (Nettention.Proud.RmiID)21154;
		public const Nettention.Proud.RmiID CG_RequestEventPaybackRewardOK = (Nettention.Proud.RmiID)21161;
		public const Nettention.Proud.RmiID CG_RequestBossWarCreateOK = (Nettention.Proud.RmiID)21300;
		public const Nettention.Proud.RmiID CG_RequestBossWarJoinOK = (Nettention.Proud.RmiID)21301;
		public const Nettention.Proud.RmiID CG_RequestBossWarStartOK = (Nettention.Proud.RmiID)21302;
		public const Nettention.Proud.RmiID CG_RequestBossWarBattleStartOK = (Nettention.Proud.RmiID)21303;
		public const Nettention.Proud.RmiID CG_RequestBossWarBattleEndOK = (Nettention.Proud.RmiID)21304;
		public const Nettention.Proud.RmiID CG_RequestBossWarOnlineFriendListOK = (Nettention.Proud.RmiID)21305;
		public const Nettention.Proud.RmiID CG_RequestBossWarOnlineGuildMemberListOK = (Nettention.Proud.RmiID)21306;
		public const Nettention.Proud.RmiID CG_RequestBossWarOnlineUserRankRangeListOK = (Nettention.Proud.RmiID)21307;
		public const Nettention.Proud.RmiID CG_RequestBossWarInvitationReceiveListOK = (Nettention.Proud.RmiID)21308;
		public const Nettention.Proud.RmiID CG_RequestBossWarRemoveInvitationOK = (Nettention.Proud.RmiID)21309;
		public const Nettention.Proud.RmiID CG_RequestBossWarInviteOK = (Nettention.Proud.RmiID)21310;
		public const Nettention.Proud.RmiID CG_RequestBossWarKickOutOK = (Nettention.Proud.RmiID)21311;
		public const Nettention.Proud.RmiID CG_RequestBossWarRewardOK = (Nettention.Proud.RmiID)21312;
		public const Nettention.Proud.RmiID CG_RequestBossWarReadyOK = (Nettention.Proud.RmiID)21313;
		public const Nettention.Proud.RmiID CG_RequestBossWarReturnReadyOK = (Nettention.Proud.RmiID)21314;
		public const Nettention.Proud.RmiID CG_RequestBossWarSyncOK = (Nettention.Proud.RmiID)21315;
		public const Nettention.Proud.RmiID CG_RequestBossWarBattleSyncOK = (Nettention.Proud.RmiID)21316;
		public const Nettention.Proud.RmiID CG_RequestBossWarLeaveOK = (Nettention.Proud.RmiID)21317;
		public const Nettention.Proud.RmiID GC_NotifyBossWarInvite = (Nettention.Proud.RmiID)21318;
		public const Nettention.Proud.RmiID GC_NotifyBossWarMemberJoinUpdate = (Nettention.Proud.RmiID)21319;
		public const Nettention.Proud.RmiID GC_NotifyBossWarGameStart = (Nettention.Proud.RmiID)21320;
		public const Nettention.Proud.RmiID GC_NotifyBossWarWaitReadyStartOK = (Nettention.Proud.RmiID)21321;
		public const Nettention.Proud.RmiID GC_NotifyBossWarRewardAggregationOK = (Nettention.Proud.RmiID)21322;
		public const Nettention.Proud.RmiID CG_RequestEventSnsShareProgressOK = (Nettention.Proud.RmiID)21162;
		public const Nettention.Proud.RmiID CG_RequestEventSnsShareRewardOK = (Nettention.Proud.RmiID)21163;
		public const Nettention.Proud.RmiID CG_RequestGagueEventInfoOK = (Nettention.Proud.RmiID)21171;
		public const Nettention.Proud.RmiID CG_RequestGagueEventChargeOK = (Nettention.Proud.RmiID)21172;
		public const Nettention.Proud.RmiID CG_RequestGagueEventRewardOK = (Nettention.Proud.RmiID)21173;
		public const Nettention.Proud.RmiID CG_RequestGagueEventResetOK = (Nettention.Proud.RmiID)21174;
		public const Nettention.Proud.RmiID CG_RequestEventLadderRewardOK = (Nettention.Proud.RmiID)21181;
		public const Nettention.Proud.RmiID CG_RequestEventLobbyGiftRewardOK = (Nettention.Proud.RmiID)21182;
		public const Nettention.Proud.RmiID CG_RequestEventTimeMissionInfoOK = (Nettention.Proud.RmiID)21191;
		public const Nettention.Proud.RmiID CG_RequestEventTimeMissionStartOK = (Nettention.Proud.RmiID)21192;
		public const Nettention.Proud.RmiID CG_RequestEventLobbyDecorationRewardOK = (Nettention.Proud.RmiID)21195;
		public const Nettention.Proud.RmiID CG_RequestRegistPlayTitleOK = (Nettention.Proud.RmiID)21201;
		public const Nettention.Proud.RmiID CG_RequestPlayTitleMissionRewardOK = (Nettention.Proud.RmiID)21202;
		public const Nettention.Proud.RmiID CG_RequestTournamentListOK = (Nettention.Proud.RmiID)21211;
		public const Nettention.Proud.RmiID CG_RequestTournamentProgressInfoOK = (Nettention.Proud.RmiID)21212;
		public const Nettention.Proud.RmiID CG_RequestTournamentResultInfoOK = (Nettention.Proud.RmiID)21213;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchJoinOK = (Nettention.Proud.RmiID)21214;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchBattleStartOK = (Nettention.Proud.RmiID)21216;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchBattleEndOK = (Nettention.Proud.RmiID)21217;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchExitOK = (Nettention.Proud.RmiID)21218;
		public const Nettention.Proud.RmiID GC_NotifyTournamentProgressChange = (Nettention.Proud.RmiID)21219;
		public const Nettention.Proud.RmiID CG_RequestTournamentRewardOK = (Nettention.Proud.RmiID)21220;
		public const Nettention.Proud.RmiID GC_NotifyTournamentMatchSuspend = (Nettention.Proud.RmiID)21221;
		public const Nettention.Proud.RmiID CG_RequestTournamentPlayerTeamSlotChangeOK = (Nettention.Proud.RmiID)21222;
		public const Nettention.Proud.RmiID CG_RequestTournamentPlayerTeamInfoOK = (Nettention.Proud.RmiID)21223;
		public const Nettention.Proud.RmiID CG_RequestTournamentCheerOK = (Nettention.Proud.RmiID)21224;
		public const Nettention.Proud.RmiID CG_RequestTournamentCheerListOK = (Nettention.Proud.RmiID)21225;
		public const Nettention.Proud.RmiID CG_RequestTournamentWatcherJoinOK = (Nettention.Proud.RmiID)21226;
		public const Nettention.Proud.RmiID CG_RequestTournamentWatcherExitOK = (Nettention.Proud.RmiID)21227;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchPlayInfoOK = (Nettention.Proud.RmiID)21228;
		public const Nettention.Proud.RmiID CG_RequestTournamentReplayInfoOK = (Nettention.Proud.RmiID)21229;
		public const Nettention.Proud.RmiID CG_RequestGuildWarLobbyInfoOK = (Nettention.Proud.RmiID)22000;
		public const Nettention.Proud.RmiID CG_RequestGuildWarRankInfoOK = (Nettention.Proud.RmiID)22001;
		public const Nettention.Proud.RmiID CG_RequestGuildWarVersusRecordInfoOK = (Nettention.Proud.RmiID)22002;
		public const Nettention.Proud.RmiID CG_RequestGuildWarGuildMemberListOK = (Nettention.Proud.RmiID)22003;
		public const Nettention.Proud.RmiID CG_RequestGuildWarWorldMapInfoOK = (Nettention.Proud.RmiID)22004;
		public const Nettention.Proud.RmiID CG_RequestGuildWarAttackSquadChangeOK = (Nettention.Proud.RmiID)22005;
		public const Nettention.Proud.RmiID CG_RequestGuildWarDefenceTeamChangeOK = (Nettention.Proud.RmiID)22006;
		public const Nettention.Proud.RmiID CG_RequestGuildWarRegionBonusScoreChangeOK = (Nettention.Proud.RmiID)22007;
		public const Nettention.Proud.RmiID CG_RequestGuildWarAreaGuildMemberChangeOK = (Nettention.Proud.RmiID)22008;
		public const Nettention.Proud.RmiID CG_RequestGuildWarBattleRecordInfoOK = (Nettention.Proud.RmiID)22009;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_StartOK = (Nettention.Proud.RmiID)22010;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_ClearOK = (Nettention.Proud.RmiID)22011;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_RejoinOK = (Nettention.Proud.RmiID)22012;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_HeroStatus_SyncOK = (Nettention.Proud.RmiID)22013;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			CG_CommonCancel,
			GC_NotifyUserLevelUp,
			CG_FrozenAssetCancel,
			CG_RequestChannelUserInfoOK,
			CG_RequestHeartBeatOK,
			CG_RequestChangeNicknameOK,
			CG_RequestChangeWantToSayOK,
			CG_RequestStageInfoOK,
			CG_RequestTeamInfoOK,
			CG_RequestTeamSlotChangeOK,
			CG_RequestTeamNameChangeOK,
			CG_RequestLobbyInfoOK,
			CG_RequestBasePointInfoOK,
			CG_RequestMercenaryListOK,
			CG_RequestMercenaryInfoOK,
			CG_RequestGuildInfoOK,
			CG_RequestChatStampUpdateBookmarkOK,
			CG_RequestChatStampUpdateQuickMessageOK,
			CG_RequestMainSkinChangeOK,
			CG_RequestEventListOK,
			CG_RequestCheatEnterOK,
			CG_RequestCheatStageClearOK,
			CG_RequestDllGetItemOK,
			CG_RequestRecommendFriendUSNListOK,
			CG_RequestDailyResetOK,
			CG_NotifyMaintenance,
			CG_RequestFrozenAssetRedeemOK,
			CG_RequestSecurityTokenOK,
			CG_RequestNetmarbleAuthOK,
			CG_RequestAuthenticateCreateOK,
			CG_RequestEditorUserInfoByNickNameOK,
			CG_RequestLoginOK,
			CG_RequestLoginInstantlyOK,
			CG_RequestForceLogoutOK,
			CG_RetryRequestOK,
			CG_RequestBillingInitializeOK,
			CG_RequestBillingVerifyPUOK,
			CG_RequestBillingRemainTROK,
			CG_RequestBillingCouponVerifyOK,
			CG_RequestBillingCrossPromotionOK,
			CG_RequestBillingPackageShopOK,
			CG_RequestAgeInputOK,
			CG_Notify_WolverineOK,
			CG_RequestSDKInfoChangeOK,
			CG_RequestSkinLevelUpBySkinMaterialOK,
			CG_RequestSkinResearchOK,
			CG_RequestSkinResearchInitOK,
			CG_RequestSkinMaterialGrindOK,
			CG_RequestSkinAwakenOK,
			CG_RequestSkinHeadStyleChangeOK,
			CG_RequestSkinEvolutionOK,
			CG_RequestSkinSkillLevelUpOK,
			CG_RequestSkinGiveFellowshipExpOK,
			CG_RequestSkinFellowshipLevelUpRewardOK,
			CG_RequestCostumeEquipOK,
			CG_RequestCostumeUnEquipOK,
			CG_RequestCostumeUnLockOK,
			CG_RequestSkinOverEvolutionOK,
			CG_RequestSkinMaxAwakenRewardOK,
			CG_RequestCostumeRegisterOK,
			CG_RequestSkinLoveRewardOK,
			CG_RequestCostumeAutoRegisterOK,
			CG_RequestStoryCostumeOK,
			CG_RequestCostumeLevelUpOK,
			CG_RequestSkinMaxAwakenOK,
			CG_RequestWeaponEquipOK,
			CG_RequestWeaponUnEquipOK,
			CG_RequestWeaponSellOK,
			CG_RequestWeaponGrindOK,
			CG_RequestWeaponUpgradeOK,
			CG_RequestWeaponUpgradeRetryOK,
			CG_RequestWeaponEvolutionOK,
			CG_RequestWeaponEvolutionRetryOK,
			CG_RequestWeaponOptionEnhanceOK,
			CG_RequestWeaponLockOK,
			CG_RequestWeaponUnLockOK,
			CG_RequestWeaponEquipExchangeOK,
			CG_RequestWeaponEquipExchangeAllOK,
			CG_RequestWeaponEquipRecommandOK,
			CG_RequestWeaponCarveOK,
			CG_RequestWeaponCarveRemoveOK,
			CG_RequestStageRejoinOK,
			CG_Request_Main_Stage_StartOK,
			CG_Request_Main_Stage_ClearOK,
			CG_Request_Main_Stage_ContinueOK,
			CG_Request_Free_Stage_StartOK,
			CG_Request_Free_Stage_ClearOK,
			CG_Request_Free_Stage_ContinueOK,
			CG_RequestHawkRunStageStartOK,
			CG_RequestHawkRunStageClearOK,
			CG_RequestEventStageClearOK,
			CG_Request_Quest_Stage_StartOK,
			CG_Request_Quest_Stage_ClearOK,
			CG_Request_Quest_Stage_ContinueOK,
			CG_Request_Week_Stage_StartOK,
			CG_Request_Week_Stage_ClearOK,
			CG_Request_Week_Stage_ContinueOK,
			CG_Request_Boss_Stage_StartOK,
			CG_Request_Boss_Stage_ClearOK,
			CG_Request_Boss_Stage_ContinueOK,
			CG_Request_Memorial_Stage_StartOK,
			CG_Request_Memorial_Stage_ClearOK,
			CG_Request_Memorial_Stage_ContinueOK,
			CG_Request_Limited_Stage_StartOK,
			CG_Request_Limited_Stage_ClearOK,
			CG_Request_Limited_Stage_ContinueOK,
			CG_Request_Main_ExtraStage_StartOK,
			CG_Request_Main_ExtraStage_ClearOK,
			CG_Request_Main_ExtraStage_ContinueOK,
			CG_Request_Boss_ExtraStage_StartOK,
			CG_Request_Boss_ExtraStage_ClearOK,
			CG_Request_Boss_ExtraStage_ContinueOK,
			CG_RequestRewardStageClearOK,
			CG_Request_AnotherMain_Stage_StartOK,
			CG_Request_AnotherMain_Stage_ClearOK,
			CG_Request_AnotherMain_Stage_ContinueOK,
			CG_Request_Reverse_Stage_StartOK,
			CG_Request_Reverse_Stage_ClearOK,
			CG_Request_Reverse_Star_RewardOK,
			CG_Request_Reverse_Group_RewardOK,
			CG_Request_Main_EventAreaStage_StartOK,
			CG_Request_Main_EventAreaStage_ClearOK,
			CG_Request_Main_EventAreaStage_ContinueOK,
			CG_Request_Free_EventAreaStage_StartOK,
			CG_Request_Free_EventAreaStage_ClearOK,
			CG_Request_Free_EventAreaStage_ContinueOK,
			CG_RequestEventAreaRewardStageClearOK,
			CG_Request_Free_EventStage_StartOK,
			CG_Request_Free_EventStage_ClearOK,
			CG_Request_Free_EventStage_ContinueOK,
			CG_RequestEventExchangeOK,
			CG_RequestEventPlayCountRewardOK,
			CG_Request_Main_ListEventStage_StartOK,
			CG_Request_Main_ListEventStage_ClearOK,
			CG_Request_Main_ListEventStage_ContinueOK,
			CG_Request_Free_ListEventStage_StartOK,
			CG_Request_Free_ListEventStage_ClearOK,
			CG_Request_Free_ListEventStage_ContinueOK,
			CG_Request_Main_FinalBossStage_StartOK,
			CG_Request_Main_FinalBossStage_ClearOK,
			CG_Request_Main_FinalBossStage_ContinueOK,
			CG_Request_FinalBoss_EventFreeStage_StartOK,
			CG_Request_FinalBoss_EventFreeStage_ClearOK,
			CG_Request_FinalBoss_EventFreeStage_ContinueOK,
			CG_Request_Limited_EventStage_StartOK,
			CG_Request_Limited_EventStage_ClearOK,
			CG_Request_Limited_EventStage_ContinueOK,
			CG_Request_Boss_EventStage_StartOK,
			CG_Request_Boss_EventStage_ClearOK,
			CG_Request_Boss_EventStage_ContinueOK,
			CG_Request_Monthly_EventStage_StartOK,
			CG_Request_Monthly_EventStage_ClearOK,
			CG_Request_Monthly_EventStage_ContinueOK,
			CG_RequestMonthlyStagePointRewardOK,
			CG_Request_ChallengeBoss_EventStage_StartOK,
			CG_Request_ChallengeBoss_EventStage_ClearOK,
			CG_Request_ChallengeBoss_EventStage_ContinueOK,
			CG_Request_ChallengeBoss_EventStage_InfoOK,
			CG_Request_ChallengeBoss_Event_Point_RewardOK,
			CG_Request_Training_Stage_InfoOK,
			CG_Request_Training_Stage_StartOK,
			CG_Request_Training_Stage_ClearOK,
			CG_Request_Training_Stage_ContinueOK,
			CG_Request_Training_Stage_OpenOK,
			CG_Request_Training_Stage_RefreshOK,
			CG_RequestWeekStageGaugeRewardOK,
			CG_RequestIngameBattleStartOK,
			CG_RequestStageEndLogOK,
			CG_Request_SingleSiege_ExtraStage_StartOK,
			CG_Request_SingleSiege_ExtraStage_ClearOK,
			CG_Request_SingleSiege_ExtraStage_ContinueOK,
			CG_Request_FinalBoss_Stage_StartOK,
			CG_Request_FinalBoss_Stage_ClearOK,
			CG_Request_FinalBoss_Stage_ContinueOK,
			CG_Request_FinalBoss_Season_InfoOK,
			CG_Request_FinalBoss_Season_Rank_InfoOK,
			CG_Request_GuildBoss_Stage_StartOK,
			CG_Request_GuildBoss_Stage_ClearOK,
			CG_Request_GuildBoss_Lobby_InfoOK,
			CG_Request_GuildBoss_Rank_InfoOK,
			CG_Request_GuildBoss_LastWeek_Rank_InfoOK,
			CG_Request_GuildBoss_Time_RefreshOK,
			CG_RequestMailListOK,
			CG_RequestMailConfirmOK,
			CG_RequestMailConfirmAllOK,
			CG_RequestMailHistoryListOK,
			CG_RequestMailRecentlyHistoryListOK,
			CG_RequestFriendMailListOK,
			CG_RequestFriendMailConfirmOK,
			CG_RequestFriendMailConfirmAllOK,
			CG_RequestNoticeMailRewardOK,
			CG_RequestPackageMailListOK,
			CG_RequestPackageMailGetOK,
			CG_RequestPackageMailHistoryListOK,
			CG_RequestLevelUpPackageRewardOK,
			CG_RequestLevelUpPackageRewardAllOK,
			CG_RequestAttendancePackageRewardOK,
			CG_RequestAttendancePackageRewardAllOK,
			CG_RequestMailADRewardOK,
			CG_RequestItemInventoryBuyOK,
			CG_RequestWeaponInventoryBuyOK,
			CG_RequestWeekStageKeyBuyOK,
			CG_RequestDiaShopInfoOK,
			CG_RequestDiaShopBuyOK,
			CG_RequestGambleShopBuyOK,
			CG_RequestItemGambleShopInfoOK,
			CG_RequestItemGambleShopBuyOK,
			CG_RequestRandomShopBuyOK,
			CG_RequestRandomShopRefreshOK,
			CG_RequestRandomShopInfoOK,
			CG_RequestBasePointShopInfoOK,
			CG_RequestBasePointShopBuyOK,
			CG_RequestArenaRealTimePvpShopInfoOK,
			CG_RequestArenaRealTimePvpShopBuyOK,
			CG_RequestCoinShopInfoOK,
			CG_RequestCoinShopBuyOK,
			CG_RequestCoinShopDailyBuyOK,
			CG_RequestCostumeShopInfoOK,
			CG_RequestCostumeShopBuyOK,
			CG_RequestFriendPointShopInfoOK,
			CG_RequestFriendPointShopBuyOK,
			CG_RequestCommonItemSellOK,
			CG_RequestCommonItemRemoveOK,
			CG_RequestPackageShopInfoOK,
			CG_RequestGambleShopInfoOK,
			CG_RequestADRouletteRewardOK,
			CG_RequestRandomShopVisitRewardOK,
			CG_RequestRandomShopScheduleInfoOK,
			CG_RequestPackageBuyOK,
			CG_RequestBuyDiaOK,
			CG_RequestBuyGoldOK,
			CG_RequestBuyStaminaOK,
			CG_RequestGuildShopInfoOK,
			CG_RequestGuildShopBuyOK,
			CG_RequestBasePointShopResetOK,
			CG_RequestArenaRealTimePvpShopResetOK,
			CG_RequestCostumeShopPackageBuyOK,
			CG_RequestFinalBossShopInfoOK,
			CG_RequestFinalBossShopBuyOK,
			CG_RequestEventCollaborationCoinShopInfoOK,
			CG_RequestEventCollaborationCoinShopBuyOK,
			CG_RequestGuildShopResetOK,
			CG_RequestCoinShopOnceBuyOK,
			CG_RequestBingoGambleShopInfoOK,
			CG_RequestBingoGambleShopResetOK,
			CG_RequestBingoGambleShopRewardOK,
			CG_RequestDiaShopPackageBuyOK,
			CG_RequestGambleChoiceShopBuyOK,
			CG_RequestFreePackageRewardOK,
			CG_RequestPackageMissionCloseOK,
			CG_RequestMissionProgressOK,
			CG_RequestMissionClearOK,
			CG_RequestMissionEventClearOK,
			CG_RequestMissionGetAchievePointRewardOK,
			CG_RequestQuestStartOK,
			CG_RequestQuestProgressOK,
			CG_RequestQuestClearOK,
			CG_RequestQuestRemoveOK,
			CG_RequestNetmarbleQuestAchieveOK,
			CG_RequestNetmarbleQuestRewardOK,
			CG_RequestDirectSelectorRewardOK,
			CG_RequestQuestChapterClearOK,
			CG_RequestEventQuestClearOK,
			CG_RequestAnotherQuestClearOK,
			CG_RequestQuestGuideListAllClearRewardOK,
			CG_RequestLobbyVRSearchOK,
			CG_RequestLobbyVRHelbramOK,
			CG_RequestLobbyNpcSkinOK,
			CG_RequestLobbyNpcGiftOK,
			CG_RequestLobbyKingAmberOK,
			CG_RequestLobbyDropInteractiveOpenOK,
			CG_RequestLobbyUniqueInteractiveOpenOK,
			CG_RequestLobbyNpcTalkInfoOK,
			CG_RequestLobbyNpcTalkChoiceOK,
			CG_RequestLobbyBarrelOK,
			CG_RequestLobbyBarrelRefillOK,
			CG_RequestLobbyCleanTableOK,
			CG_RequestLobbyServeBeerOK,
			CG_RequestLobbyPlayJukeboxOK,
			CG_RequestLobbyElizabethTouchOK,
			CG_RequestLobbyHawkAngerOK,
			CG_RequestAttendanceRewardOK,
			CG_RequestAttendanceEventRewardOK,
			CG_RequestCookingStartOK,
			CG_RequestRecipeActiveOK,
			CG_RequestCookingRecipeOrderInfoOK,
			CG_RequestCookingRecipeOrderOK,
			CG_RequestCookingRecipeDisorderOK,
			CG_RequestCookingRecipeCollectOK,
			CG_RequestCookingRecipeCollectOneSlotOK,
			CG_RequestCookingUseCookingBuffOK,
			CG_RequestGuestInfoOK,
			CG_RequestGuestChangeOK,
			CG_RequestGuestChangeTargetOK,
			CG_RequestGuestTalkOK,
			CG_RequestGuestGiftOK,
			CG_RequestBirthdayNpcInfoOK,
			CG_RequestRestRewardOK,
			CG_RequestAttendanceFortuneEventRewardOK,
			CG_RequestBasePointGoldDonationOK,
			CG_RequestBasePointSetTriggerOK,
			CG_RequestBasePointDropInteractiveOpenOK,
			CG_RequestBasePointUniqueInteractiveOpenOK,
			CG_RequestBasePointDailyRewardOK,
			CG_RequestBasePointDonationEventRewardOK,
			CG_RequestBasePointDonationInfoOK,
			CG_RequestBasePointEventGoldDonationOK,
			CG_RequestEventBasepointInfoOK,
			GC_NotifyDestroyInvite,
			CG_RequestDestroySetInviteOptionOK,
			CG_RequestDestroyGetUserLoginListOK,
			CG_RequestDestroyGetFriendLoginListOK,
			CG_RequestDestroyGetGuildLoginListOK,
			CG_RequestDestroyGetReceivedInvitationListOK,
			CG_RequestDestroyInviteOK,
			CG_RequestDestroyRemoveInvitationOK,
			CG_RequestDestroyRemoveJoinInfoOK,
			CG_RequestDestroyCreateOK,
			CG_RequestDestroyStartOK,
			CG_RequestDestroyBattleStartOK,
			CG_RequestDestroyJoinOK,
			CG_RequestDestroyClearOK,
			CG_RequestDestroyReJoinOK,
			CG_RequestDestroyRemoveOK,
			CG_RequestDestroyBattleEndOK,
			CG_RequestDestroyInviteAIOK,
			CG_RequestDestroyKickOutAIOK,
			CG_RequestEventDestroyCreateOK,
			CG_RequestEventDestroyClearOK,
			CG_RequestEventDestroyStartOK,
			CG_RequestEventDestroyRemoveOK,
			CG_RequestEventChallengeDestroyCreateOK,
			CG_RequestEventChallengeDestroyStartOK,
			CG_RequestEventChallengeDestroyClearOK,
			CG_RequestEventChallengeDestroyPointRefreshOK,
			CG_RequestEventChallengeDestroyUserRewardOK,
			CG_RequestEventChallengeDestroyWorldRewardOK,
			CG_RequestFriendListOK,
			CG_RequestFriendGuildInfoOK,
			CG_RequestFriendApplySendListOK,
			CG_RequestFriendApplyReceiveListOK,
			CG_RequestFriendApplySendOK,
			CG_RequestFriendApplyRejectOK,
			CG_RequestFriendApplyReceiveAcceptOK,
			CG_RequestFriendApplyReceiveAcceptListOK,
			CG_RequestFriendApplyReceiveRefuseOK,
			CG_RequestFriendApplyReceiveRefuseListOK,
			CG_RequestFriendRemoveOK,
			CG_RequestFriendSearchOK,
			CG_RequestFriendVisitOK,
			CG_RequestFriendPointSendOK,
			CG_RequestFriendPointSendAllOK,
			CG_RequestFriendLobbyInfoOK,
			CG_RequestFriendCookingRecipeInfoOK,
			CG_RequestFriendCookingEatOK,
			CG_RequestFriendCookingEatFriendListOK,
			CG_RequestGuildRecommendListOK,
			CG_RequestGuildInfoWithMemberListOK,
			CG_RequestGuildSearchByNameOK,
			CG_RequestGuildCreateOK,
			CG_RequestGuildDisbandOK,
			CG_RequestGuildApplicantListOK,
			CG_RequestGuildApplyOK,
			CG_RequestGuildReturnApplicationOK,
			CG_RequestGuildAcceptApplicantOK,
			CG_RequestGuildRejectApplicantOK,
			CG_RequestGuildLevelUpOK,
			CG_RequestGuildChangeNameOK,
			CG_RequestGuildChangeBoardOK,
			CG_RequestGuildChangeMasterOK,
			CG_RequestGuildChangeMemberGradeOK,
			CG_RequestGuildKickOutMemberOK,
			CG_RequestGuildLeaveOK,
			CG_RequestGuildRoomInfoOK,
			CG_RequestGuildAttendanceOK,
			CG_RequestGuildAttendanceRewardOK,
			CG_RequestGuildUserInfoOK,
			CG_RequestGuildAttendanceStatusOK,
			GC_NotifyGuildKickout,
			CG_RequestGuildDonationOK,
			CG_RequestGuildDonationInitializeOK,
			CG_RequestGuildMissionInfoOK,
			CG_RequestGuildMissionRewardOK,
			GC_NotifyGuildAcceptApplicantOK,
			CG_RequestGuildDonationInfoOK,
			CG_RequestGuildSkillInfoOK,
			CG_RequestGuildSkillLevelUpOK,
			CG_RequestGuildSkillUseOK,
			CG_RequestGuildSkillDisuseOK,
			CG_RequestGuildSkillUseInfoOK,
			CG_RequestGuildMemberRankPointRewardOK,
			CG_RequestGuildBattlePointRegisterOK,
			CG_RequestGuildBattlePointMemeberRankListOK,
			CG_RequestGuildBattlePointGuildRankListOK,
			CG_RequestGuildBattlePointUserRankListOK,
			CG_RequestAPRechargeByUseItemOK,
			CG_RequestWeekStageKeyOpenOK,
			CG_RequestFoodBuffAutoUseOnOffOK,
			CG_RequestItemUseRankExpOK,
			CG_RequestItemUseBoxOpenOK,
			CG_RequestItemUseRecipeExpOK,
			CG_RequestItemUseWeeklyKeyBoxOK,
			CG_RequestItemUseWeaponTicketOK,
			CG_RequestItemUseMusicOK,
			CG_RequestTutorialAddStepOK,
			CG_RequestTutorialSetFlagOK,
			CG_RequestTutorialHeroFlagOK,
			CG_RequestTutorialGambleShopBuyOK,
			CG_RequestBattleTutorialInfoOK,
			CG_RequestBattleTutorialSetOK,
			CG_RequestFriendlyMatchCreateOK,
			CG_RequestFriendlyMatchFriendListOK,
			CG_RequestFriendlyMatchInviteOK,
			CG_RequestFriendlyMatchReceivedInviteListOK,
			CG_RequestFriendlyMatchInviteAcceptOK,
			CG_RequestFriendlyMatchInviteRejectOK,
			CG_RequestFriendlyMatchStartOK,
			CG_RequestFriendlyMatchBattleStartOK,
			CG_RequestFriendlyMatchClearOK,
			CG_RequestFriendlyMatchExitOK,
			GC_NotifyFriendlyMatchInvite,
			CG_RequestFriendlyMatchSetInviteOptionOK,
			CG_RequestEventMissionGetAchievePointRewardOK,
			CG_RequestEventMissionCompleteRewardOK,
			CG_RequestEventMissionInfoOk,
			CG_RequestLobbyHousingShopInfoOK,
			CG_RequestLobbyHousingShopBuyOK,
			CG_RequestLobbyFurnitureRegistOK,
			CG_RequestUserMusicEditOK,
			CG_RequestEventSeasonPassInfoOK,
			CG_RequestEventSeasonPassRankUpRewardOK,
			CG_RequestEventSeasonPassRankUpRewardAllOK,
			CG_RequestEventSeasonPassRankBuyOK,
			CG_RequestStepupGambleShopBuyOK,
			CG_RequestStepupGambleMileageRewardOK,
			CG_RequestWestSideServerInfo_RandomOK,
			CG_RequestWestSideServerInfo_FixedOK,
			CG_RequestWestSideServerInfo_RecommandOK,
			CG_RequestWestSide_PlayerInfoOK,
			CG_RequestWestSide_PlayerteamInfoOK,
			CG_RequestWestSide_PlayerGuildInfoOK,
			CG_RequestWorldChattingChannelOK,
			CG_RequestArenaRealTimePvpLobbyInfoOK,
			CG_RequestArenaRealTimePvpJoinOK,
			CG_RequestArenaRealTimePvpTopRankerListOK,
			CG_RequestArenaRealTimePvpLastRankerListOK,
			CG_RequestArenaRealTimePvpMatchingOK,
			CG_RequestArenaRealTimePvpBattleStartOK,
			CG_RequestArenaRealTimePvpBattleEndOK,
			CG_RequestArenaRealTimePvpRollbackOK,
			CG_RequestArenaRealTimePvpIngameBattleStartOK,
			CG_RequestArenaRealTimePvpLowerLobbyInfoOK,
			CG_RequestArenaRealTimePvpLowerJoinOK,
			CG_RequestArenaRealTimePvpLowerTopRankerListOK,
			CG_RequestArenaRealTimePvpLowerMatchingOK,
			CG_RequestArenaRealTimePvpLowerBattleStartOK,
			CG_RequestArenaRealTimePvpLowerBattleEndOK,
			CG_RequestArenaRealTimePvpAllInfoOK,
			CG_RequestArenaRealTimePvpLastRankerBattleInfoOK,
			CG_RequestArenaRealTimePvpLastRankerBattleStartOK,
			CG_RequestArenaRealTimePvpLowerRollbackOK,
			CG_RequestArenaRealTimePvpLowerIngameBattleStartOK,
			CG_RequestArenaRealTimeDecisionLobbyInfoOK,
			CG_RequestArenaRealTimeDecisionJoinOK,
			CG_RequestArenaRealTimeDecisionTopRankerListOK,
			CG_RequestArenaRealTimeDecisionMatchingOK,
			CG_RequestArenaRealTimeDecisionBattleStartOK,
			CG_RequestArenaRealTimeDecisionBattleEndOK,
			CG_RequestArenaRealTimeDecisionIngameBattleStartOK,
			CG_RequestArenaRealTimeDecisionHistoryOK,
			CG_RequestArenaRealTimeDecisionChangeMatchingListOK,
			CG_RequestArenaRealTimeDecisionMatchingSimpleInfoOK,
			CG_RequestPvpSeasonInfoOK,
			CG_RequestPvpSeasonHistoryOK,
			CG_RequestEventExchangeInfoOK,
			CG_RequestEventExchangeBoxGachaInfoOK,
			CG_RequestEventExchangeBoxGachaPickupOK,
			CG_RequestEventExchangeBoxGachaResetOK,
			CG_RequestEventPaybackRewardOK,
			CG_RequestBossWarCreateOK,
			CG_RequestBossWarJoinOK,
			CG_RequestBossWarStartOK,
			CG_RequestBossWarBattleStartOK,
			CG_RequestBossWarBattleEndOK,
			CG_RequestBossWarOnlineFriendListOK,
			CG_RequestBossWarOnlineGuildMemberListOK,
			CG_RequestBossWarOnlineUserRankRangeListOK,
			CG_RequestBossWarInvitationReceiveListOK,
			CG_RequestBossWarRemoveInvitationOK,
			CG_RequestBossWarInviteOK,
			CG_RequestBossWarKickOutOK,
			CG_RequestBossWarRewardOK,
			CG_RequestBossWarReadyOK,
			CG_RequestBossWarReturnReadyOK,
			CG_RequestBossWarSyncOK,
			CG_RequestBossWarBattleSyncOK,
			CG_RequestBossWarLeaveOK,
			GC_NotifyBossWarInvite,
			GC_NotifyBossWarMemberJoinUpdate,
			GC_NotifyBossWarGameStart,
			GC_NotifyBossWarWaitReadyStartOK,
			GC_NotifyBossWarRewardAggregationOK,
			CG_RequestEventSnsShareProgressOK,
			CG_RequestEventSnsShareRewardOK,
			CG_RequestGagueEventInfoOK,
			CG_RequestGagueEventChargeOK,
			CG_RequestGagueEventRewardOK,
			CG_RequestGagueEventResetOK,
			CG_RequestEventLadderRewardOK,
			CG_RequestEventLobbyGiftRewardOK,
			CG_RequestEventTimeMissionInfoOK,
			CG_RequestEventTimeMissionStartOK,
			CG_RequestEventLobbyDecorationRewardOK,
			CG_RequestRegistPlayTitleOK,
			CG_RequestPlayTitleMissionRewardOK,
			CG_RequestTournamentListOK,
			CG_RequestTournamentProgressInfoOK,
			CG_RequestTournamentResultInfoOK,
			CG_RequestTournamentMatchJoinOK,
			CG_RequestTournamentMatchBattleStartOK,
			CG_RequestTournamentMatchBattleEndOK,
			CG_RequestTournamentMatchExitOK,
			GC_NotifyTournamentProgressChange,
			CG_RequestTournamentRewardOK,
			GC_NotifyTournamentMatchSuspend,
			CG_RequestTournamentPlayerTeamSlotChangeOK,
			CG_RequestTournamentPlayerTeamInfoOK,
			CG_RequestTournamentCheerOK,
			CG_RequestTournamentCheerListOK,
			CG_RequestTournamentWatcherJoinOK,
			CG_RequestTournamentWatcherExitOK,
			CG_RequestTournamentMatchPlayInfoOK,
			CG_RequestTournamentReplayInfoOK,
			CG_RequestGuildWarLobbyInfoOK,
			CG_RequestGuildWarRankInfoOK,
			CG_RequestGuildWarVersusRecordInfoOK,
			CG_RequestGuildWarGuildMemberListOK,
			CG_RequestGuildWarWorldMapInfoOK,
			CG_RequestGuildWarAttackSquadChangeOK,
			CG_RequestGuildWarDefenceTeamChangeOK,
			CG_RequestGuildWarRegionBonusScoreChangeOK,
			CG_RequestGuildWarAreaGuildMemberChangeOK,
			CG_RequestGuildWarBattleRecordInfoOK,
			CG_Request_GuildWar_Stage_StartOK,
			CG_Request_GuildWar_Stage_ClearOK,
			CG_Request_GuildWar_Stage_RejoinOK,
			CG_Request_GuildWar_Stage_HeroStatus_SyncOK,
		};
	}
}

				 
