 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace SevenDSGameC2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
		public const Nettention.Proud.RmiID CG_RequestChannelUserInfo = (Nettention.Proud.RmiID)15000;
		public const Nettention.Proud.RmiID CG_RequestHeartBeat = (Nettention.Proud.RmiID)15001;
		public const Nettention.Proud.RmiID CG_RequestChangeNickname = (Nettention.Proud.RmiID)15002;
		public const Nettention.Proud.RmiID CG_RequestChangeWantToSay = (Nettention.Proud.RmiID)15003;
		public const Nettention.Proud.RmiID CG_RequestTeamInfo = (Nettention.Proud.RmiID)15004;
		public const Nettention.Proud.RmiID CG_RequestTeamSlotChange = (Nettention.Proud.RmiID)15005;
		public const Nettention.Proud.RmiID CG_RequestTeamNameChange = (Nettention.Proud.RmiID)15006;
		public const Nettention.Proud.RmiID CG_RequestLobbyInfo = (Nettention.Proud.RmiID)15007;
		public const Nettention.Proud.RmiID CG_RequestBasePointInfo = (Nettention.Proud.RmiID)15008;
		public const Nettention.Proud.RmiID CG_RequestMercenaryList = (Nettention.Proud.RmiID)15009;
		public const Nettention.Proud.RmiID CG_RequestMercenaryInfo = (Nettention.Proud.RmiID)15010;
		public const Nettention.Proud.RmiID CG_RequestGuildInfo = (Nettention.Proud.RmiID)15011;
		public const Nettention.Proud.RmiID CG_RequestChatStampUpdateBookmark = (Nettention.Proud.RmiID)15012;
		public const Nettention.Proud.RmiID CG_RequestChatStampUpdateQuickMessage = (Nettention.Proud.RmiID)15013;
		public const Nettention.Proud.RmiID CG_RequestMainSkinChange = (Nettention.Proud.RmiID)15014;
		public const Nettention.Proud.RmiID CG_RequestEventList = (Nettention.Proud.RmiID)15015;
		public const Nettention.Proud.RmiID CG_RequestCheatEnter = (Nettention.Proud.RmiID)15016;
		public const Nettention.Proud.RmiID CG_RequestCheatStageClear = (Nettention.Proud.RmiID)15017;
		public const Nettention.Proud.RmiID CG_RequestDllGetItem = (Nettention.Proud.RmiID)15018;
		public const Nettention.Proud.RmiID CG_RequestRecommendFriendUSNList = (Nettention.Proud.RmiID)15019;
		public const Nettention.Proud.RmiID CG_RequestDailyReset = (Nettention.Proud.RmiID)15020;
		public const Nettention.Proud.RmiID CG_RequestFrozenAssetRedeem = (Nettention.Proud.RmiID)15021;
		public const Nettention.Proud.RmiID CG_RequestSecurityToken = (Nettention.Proud.RmiID)15101;
		public const Nettention.Proud.RmiID CG_RequestNetmarbleAuth = (Nettention.Proud.RmiID)15102;
		public const Nettention.Proud.RmiID CG_RequestAuthenticateCreate = (Nettention.Proud.RmiID)15103;
		public const Nettention.Proud.RmiID CG_RequestEditorUserInfoByNickName = (Nettention.Proud.RmiID)15104;
		public const Nettention.Proud.RmiID CG_RequestLogin = (Nettention.Proud.RmiID)15105;
		public const Nettention.Proud.RmiID CG_RequestLoginInstantly = (Nettention.Proud.RmiID)15106;
		public const Nettention.Proud.RmiID CG_RetryRequest = (Nettention.Proud.RmiID)15107;
		public const Nettention.Proud.RmiID CG_RequestBillingInitialize = (Nettention.Proud.RmiID)15151;
		public const Nettention.Proud.RmiID CG_RequestBillingVerifyPU = (Nettention.Proud.RmiID)15152;
		public const Nettention.Proud.RmiID CG_RequestBillingRemainTR = (Nettention.Proud.RmiID)15153;
		public const Nettention.Proud.RmiID CG_RequestBillingCouponVerify = (Nettention.Proud.RmiID)15154;
		public const Nettention.Proud.RmiID CG_RequestBillingCrossPromotion = (Nettention.Proud.RmiID)15155;
		public const Nettention.Proud.RmiID CG_RequestBillingPackageShop = (Nettention.Proud.RmiID)15156;
		public const Nettention.Proud.RmiID CG_RequestAgeInput = (Nettention.Proud.RmiID)15157;
		public const Nettention.Proud.RmiID CG_RequestSDKInfoChange = (Nettention.Proud.RmiID)15158;
		public const Nettention.Proud.RmiID CG_RequestSkinLevelUpBySkinMaterial = (Nettention.Proud.RmiID)15201;
		public const Nettention.Proud.RmiID CG_RequestSkinResearch = (Nettention.Proud.RmiID)15202;
		public const Nettention.Proud.RmiID CG_RequestSkinResearchInit = (Nettention.Proud.RmiID)15203;
		public const Nettention.Proud.RmiID CG_RequestSkinMaterialGrind = (Nettention.Proud.RmiID)15204;
		public const Nettention.Proud.RmiID CG_RequestSkinAwaken = (Nettention.Proud.RmiID)15205;
		public const Nettention.Proud.RmiID CG_RequestSkinHeadStyleChange = (Nettention.Proud.RmiID)15207;
		public const Nettention.Proud.RmiID CG_RequestSkinEvolution = (Nettention.Proud.RmiID)15209;
		public const Nettention.Proud.RmiID CG_RequestSkinSkillLevelUp = (Nettention.Proud.RmiID)15210;
		public const Nettention.Proud.RmiID CG_RequestSkinGiveFellowshipExp = (Nettention.Proud.RmiID)15211;
		public const Nettention.Proud.RmiID CG_RequestSkinFellowshipLevelUpReward = (Nettention.Proud.RmiID)15212;
		public const Nettention.Proud.RmiID CG_RequestCostumeEquip = (Nettention.Proud.RmiID)15213;
		public const Nettention.Proud.RmiID CG_RequestCostumeUnEquip = (Nettention.Proud.RmiID)15214;
		public const Nettention.Proud.RmiID CG_RequestCostumeUnLock = (Nettention.Proud.RmiID)15215;
		public const Nettention.Proud.RmiID CG_RequestSkinOverEvolution = (Nettention.Proud.RmiID)15216;
		public const Nettention.Proud.RmiID CG_RequestSkinMaxAwakenReward = (Nettention.Proud.RmiID)15217;
		public const Nettention.Proud.RmiID CG_RequestCostumeRegister = (Nettention.Proud.RmiID)15218;
		public const Nettention.Proud.RmiID CG_RequestSkinLoveReward = (Nettention.Proud.RmiID)15219;
		public const Nettention.Proud.RmiID CG_RequestCostumeAutoRegister = (Nettention.Proud.RmiID)15220;
		public const Nettention.Proud.RmiID CG_RequestStoryCostume = (Nettention.Proud.RmiID)15221;
		public const Nettention.Proud.RmiID CG_RequestCostumeLevelUp = (Nettention.Proud.RmiID)15222;
		public const Nettention.Proud.RmiID CG_RequestSkinMaxAwaken = (Nettention.Proud.RmiID)15223;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquip = (Nettention.Proud.RmiID)15251;
		public const Nettention.Proud.RmiID CG_RequestWeaponUnEquip = (Nettention.Proud.RmiID)15252;
		public const Nettention.Proud.RmiID CG_RequestWeaponSell = (Nettention.Proud.RmiID)15253;
		public const Nettention.Proud.RmiID CG_RequestWeaponGrind = (Nettention.Proud.RmiID)15254;
		public const Nettention.Proud.RmiID CG_RequestWeaponUpgrade = (Nettention.Proud.RmiID)15255;
		public const Nettention.Proud.RmiID CG_RequestWeaponUpgradeRetry = (Nettention.Proud.RmiID)15256;
		public const Nettention.Proud.RmiID CG_RequestWeaponEvolution = (Nettention.Proud.RmiID)15257;
		public const Nettention.Proud.RmiID CG_RequestWeaponEvolutionRetry = (Nettention.Proud.RmiID)15258;
		public const Nettention.Proud.RmiID CG_RequestWeaponOptionEnhance = (Nettention.Proud.RmiID)15259;
		public const Nettention.Proud.RmiID CG_RequestWeaponLock = (Nettention.Proud.RmiID)15260;
		public const Nettention.Proud.RmiID CG_RequestWeaponUnLock = (Nettention.Proud.RmiID)15261;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquipExchange = (Nettention.Proud.RmiID)15262;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquipExchangeAll = (Nettention.Proud.RmiID)15263;
		public const Nettention.Proud.RmiID CG_RequestWeaponEquipRecommand = (Nettention.Proud.RmiID)15264;
		public const Nettention.Proud.RmiID CG_RequestWeaponCarve = (Nettention.Proud.RmiID)15265;
		public const Nettention.Proud.RmiID CG_RequestWeaponCarveRemove = (Nettention.Proud.RmiID)15266;
		public const Nettention.Proud.RmiID CG_RequestStageInfo = (Nettention.Proud.RmiID)15301;
		public const Nettention.Proud.RmiID CG_RequestStageRejoin = (Nettention.Proud.RmiID)15302;
		public const Nettention.Proud.RmiID CG_Request_Week_Stage_Start = (Nettention.Proud.RmiID)15303;
		public const Nettention.Proud.RmiID CG_Request_Week_Stage_Clear = (Nettention.Proud.RmiID)15304;
		public const Nettention.Proud.RmiID CG_Request_Week_Stage_Continue = (Nettention.Proud.RmiID)15305;
		public const Nettention.Proud.RmiID CG_Request_Main_Stage_Start = (Nettention.Proud.RmiID)15306;
		public const Nettention.Proud.RmiID CG_Request_Main_Stage_Clear = (Nettention.Proud.RmiID)15307;
		public const Nettention.Proud.RmiID CG_Request_Main_Stage_Continue = (Nettention.Proud.RmiID)15308;
		public const Nettention.Proud.RmiID CG_Request_Free_Stage_Start = (Nettention.Proud.RmiID)15309;
		public const Nettention.Proud.RmiID CG_Request_Free_Stage_Clear = (Nettention.Proud.RmiID)15310;
		public const Nettention.Proud.RmiID CG_Request_Free_Stage_Continue = (Nettention.Proud.RmiID)15311;
		public const Nettention.Proud.RmiID CG_RequestHawkRunStageStart = (Nettention.Proud.RmiID)15312;
		public const Nettention.Proud.RmiID CG_RequestHawkRunStageClear = (Nettention.Proud.RmiID)15313;
		public const Nettention.Proud.RmiID CG_RequestEventStageClear = (Nettention.Proud.RmiID)15314;
		public const Nettention.Proud.RmiID CG_Request_Quest_Stage_Start = (Nettention.Proud.RmiID)15315;
		public const Nettention.Proud.RmiID CG_Request_Quest_Stage_Clear = (Nettention.Proud.RmiID)15316;
		public const Nettention.Proud.RmiID CG_Request_Quest_Stage_Continue = (Nettention.Proud.RmiID)15317;
		public const Nettention.Proud.RmiID CG_Request_Boss_Stage_Start = (Nettention.Proud.RmiID)15318;
		public const Nettention.Proud.RmiID CG_Request_Boss_Stage_Clear = (Nettention.Proud.RmiID)15319;
		public const Nettention.Proud.RmiID CG_Request_Boss_Stage_Continue = (Nettention.Proud.RmiID)15320;
		public const Nettention.Proud.RmiID CG_Request_Memorial_Stage_Start = (Nettention.Proud.RmiID)15321;
		public const Nettention.Proud.RmiID CG_Request_Memorial_Stage_Clear = (Nettention.Proud.RmiID)15322;
		public const Nettention.Proud.RmiID CG_Request_Memorial_Stage_Continue = (Nettention.Proud.RmiID)15323;
		public const Nettention.Proud.RmiID CG_Request_Limited_Stage_Start = (Nettention.Proud.RmiID)15324;
		public const Nettention.Proud.RmiID CG_Request_Limited_Stage_Clear = (Nettention.Proud.RmiID)15325;
		public const Nettention.Proud.RmiID CG_Request_Limited_Stage_Continue = (Nettention.Proud.RmiID)15326;
		public const Nettention.Proud.RmiID CG_Request_Main_ExtraStage_Start = (Nettention.Proud.RmiID)15327;
		public const Nettention.Proud.RmiID CG_Request_Main_ExtraStage_Clear = (Nettention.Proud.RmiID)15328;
		public const Nettention.Proud.RmiID CG_Request_Main_ExtraStage_Continue = (Nettention.Proud.RmiID)15329;
		public const Nettention.Proud.RmiID CG_Request_Boss_ExtraStage_Start = (Nettention.Proud.RmiID)15330;
		public const Nettention.Proud.RmiID CG_Request_Boss_ExtraStage_Clear = (Nettention.Proud.RmiID)15331;
		public const Nettention.Proud.RmiID CG_Request_Boss_ExtraStage_Continue = (Nettention.Proud.RmiID)15332;
		public const Nettention.Proud.RmiID CG_RequestRewardStageClear = (Nettention.Proud.RmiID)15333;
		public const Nettention.Proud.RmiID CG_Request_SingleSiege_ExtraStage_Start = (Nettention.Proud.RmiID)15334;
		public const Nettention.Proud.RmiID CG_Request_SingleSiege_ExtraStage_Clear = (Nettention.Proud.RmiID)15335;
		public const Nettention.Proud.RmiID CG_Request_SingleSiege_ExtraStage_Continue = (Nettention.Proud.RmiID)15336;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Stage_Start = (Nettention.Proud.RmiID)15337;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Stage_Clear = (Nettention.Proud.RmiID)15338;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Stage_Continue = (Nettention.Proud.RmiID)15339;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Season_Info = (Nettention.Proud.RmiID)15340;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_Info = (Nettention.Proud.RmiID)15341;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_Start = (Nettention.Proud.RmiID)15342;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_Clear = (Nettention.Proud.RmiID)15343;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_Continue = (Nettention.Proud.RmiID)15344;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_Open = (Nettention.Proud.RmiID)15345;
		public const Nettention.Proud.RmiID CG_Request_Training_Stage_Refresh = (Nettention.Proud.RmiID)15346;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Stage_Start = (Nettention.Proud.RmiID)15348;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Stage_Clear = (Nettention.Proud.RmiID)15349;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Lobby_Info = (Nettention.Proud.RmiID)15350;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Rank_Info = (Nettention.Proud.RmiID)15351;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_LastWeek_Rank_Info = (Nettention.Proud.RmiID)15352;
		public const Nettention.Proud.RmiID CG_Request_GuildBoss_Time_Refresh = (Nettention.Proud.RmiID)15353;
		public const Nettention.Proud.RmiID CG_Request_AnotherMain_Stage_Start = (Nettention.Proud.RmiID)15354;
		public const Nettention.Proud.RmiID CG_Request_AnotherMain_Stage_Clear = (Nettention.Proud.RmiID)15355;
		public const Nettention.Proud.RmiID CG_Request_AnotherMain_Stage_Continue = (Nettention.Proud.RmiID)15356;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_Season_Rank_Info = (Nettention.Proud.RmiID)15357;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Stage_Start = (Nettention.Proud.RmiID)15358;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Stage_Clear = (Nettention.Proud.RmiID)15359;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Star_Reward = (Nettention.Proud.RmiID)15360;
		public const Nettention.Proud.RmiID CG_Request_Reverse_Group_Reward = (Nettention.Proud.RmiID)15361;
		public const Nettention.Proud.RmiID CG_Request_Main_EventAreaStage_Start = (Nettention.Proud.RmiID)15501;
		public const Nettention.Proud.RmiID CG_Request_Main_EventAreaStage_Clear = (Nettention.Proud.RmiID)15502;
		public const Nettention.Proud.RmiID CG_Request_Main_EventAreaStage_Continue = (Nettention.Proud.RmiID)15503;
		public const Nettention.Proud.RmiID CG_Request_Free_EventAreaStage_Start = (Nettention.Proud.RmiID)15504;
		public const Nettention.Proud.RmiID CG_Request_Free_EventAreaStage_Clear = (Nettention.Proud.RmiID)15505;
		public const Nettention.Proud.RmiID CG_Request_Free_EventAreaStage_Continue = (Nettention.Proud.RmiID)15506;
		public const Nettention.Proud.RmiID CG_RequestEventAreaRewardStageClear = (Nettention.Proud.RmiID)15507;
		public const Nettention.Proud.RmiID CG_Request_Free_EventStage_Start = (Nettention.Proud.RmiID)15508;
		public const Nettention.Proud.RmiID CG_Request_Free_EventStage_Clear = (Nettention.Proud.RmiID)15509;
		public const Nettention.Proud.RmiID CG_Request_Free_EventStage_Continue = (Nettention.Proud.RmiID)15510;
		public const Nettention.Proud.RmiID CG_RequestEventExchange = (Nettention.Proud.RmiID)15511;
		public const Nettention.Proud.RmiID CG_RequestEventPlayCountReward = (Nettention.Proud.RmiID)15512;
		public const Nettention.Proud.RmiID CG_Request_Main_ListEventStage_Start = (Nettention.Proud.RmiID)15513;
		public const Nettention.Proud.RmiID CG_Request_Main_ListEventStage_Clear = (Nettention.Proud.RmiID)15514;
		public const Nettention.Proud.RmiID CG_Request_Main_ListEventStage_Continue = (Nettention.Proud.RmiID)15515;
		public const Nettention.Proud.RmiID CG_Request_Free_ListEventStage_Start = (Nettention.Proud.RmiID)15516;
		public const Nettention.Proud.RmiID CG_Request_Free_ListEventStage_Clear = (Nettention.Proud.RmiID)15517;
		public const Nettention.Proud.RmiID CG_Request_Free_ListEventStage_Continue = (Nettention.Proud.RmiID)15518;
		public const Nettention.Proud.RmiID CG_Request_Main_FinalBossStage_Start = (Nettention.Proud.RmiID)15519;
		public const Nettention.Proud.RmiID CG_Request_Main_FinalBossStage_Clear = (Nettention.Proud.RmiID)15520;
		public const Nettention.Proud.RmiID CG_Request_Main_FinalBossStage_Continue = (Nettention.Proud.RmiID)15521;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_EventFreeStage_Start = (Nettention.Proud.RmiID)15522;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_EventFreeStage_Clear = (Nettention.Proud.RmiID)15523;
		public const Nettention.Proud.RmiID CG_Request_FinalBoss_EventFreeStage_Continue = (Nettention.Proud.RmiID)15524;
		public const Nettention.Proud.RmiID CG_Request_Limited_EventStage_Start = (Nettention.Proud.RmiID)15525;
		public const Nettention.Proud.RmiID CG_Request_Limited_EventStage_Clear = (Nettention.Proud.RmiID)15526;
		public const Nettention.Proud.RmiID CG_Request_Limited_EventStage_Continue = (Nettention.Proud.RmiID)15527;
		public const Nettention.Proud.RmiID CG_Request_Boss_EventStage_Start = (Nettention.Proud.RmiID)15528;
		public const Nettention.Proud.RmiID CG_Request_Boss_EventStage_Clear = (Nettention.Proud.RmiID)15529;
		public const Nettention.Proud.RmiID CG_Request_Boss_EventStage_Continue = (Nettention.Proud.RmiID)15530;
		public const Nettention.Proud.RmiID CG_Request_Monthly_EventStage_Start = (Nettention.Proud.RmiID)15531;
		public const Nettention.Proud.RmiID CG_Request_Monthly_EventStage_Clear = (Nettention.Proud.RmiID)15532;
		public const Nettention.Proud.RmiID CG_Request_Monthly_EventStage_Continue = (Nettention.Proud.RmiID)15533;
		public const Nettention.Proud.RmiID CG_RequestMonthlyStagePointReward = (Nettention.Proud.RmiID)15534;
		public const Nettention.Proud.RmiID CG_RequestWeekStageGaugeReward = (Nettention.Proud.RmiID)15535;
		public const Nettention.Proud.RmiID CG_RequestIngameBattleStart = (Nettention.Proud.RmiID)15536;
		public const Nettention.Proud.RmiID CG_RequestStageEndLog = (Nettention.Proud.RmiID)15537;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_Start = (Nettention.Proud.RmiID)15538;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_Clear = (Nettention.Proud.RmiID)15539;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_Continue = (Nettention.Proud.RmiID)15540;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_EventStage_Info = (Nettention.Proud.RmiID)15541;
		public const Nettention.Proud.RmiID CG_Request_ChallengeBoss_Event_Point_Reward = (Nettention.Proud.RmiID)15542;
		public const Nettention.Proud.RmiID CG_RequestMailList = (Nettention.Proud.RmiID)15601;
		public const Nettention.Proud.RmiID CG_RequestMailConfirm = (Nettention.Proud.RmiID)15602;
		public const Nettention.Proud.RmiID CG_RequestMailConfirmAll = (Nettention.Proud.RmiID)15603;
		public const Nettention.Proud.RmiID CG_RequestMailHistoryList = (Nettention.Proud.RmiID)15604;
		public const Nettention.Proud.RmiID CG_RequestMailRecentlyHistoryList = (Nettention.Proud.RmiID)15605;
		public const Nettention.Proud.RmiID CG_RequestFriendMailList = (Nettention.Proud.RmiID)15606;
		public const Nettention.Proud.RmiID CG_RequestFriendMailConfirm = (Nettention.Proud.RmiID)15607;
		public const Nettention.Proud.RmiID CG_RequestFriendMailConfirmAll = (Nettention.Proud.RmiID)15608;
		public const Nettention.Proud.RmiID CG_RequestNoticeMailReward = (Nettention.Proud.RmiID)15609;
		public const Nettention.Proud.RmiID CG_RequestPackageMailList = (Nettention.Proud.RmiID)15610;
		public const Nettention.Proud.RmiID CG_RequestPackageMailGet = (Nettention.Proud.RmiID)15611;
		public const Nettention.Proud.RmiID CG_RequestPackageMailHistoryList = (Nettention.Proud.RmiID)15612;
		public const Nettention.Proud.RmiID CG_RequestLevelUpPackageReward = (Nettention.Proud.RmiID)15613;
		public const Nettention.Proud.RmiID CG_RequestLevelUpPackageRewardAll = (Nettention.Proud.RmiID)15614;
		public const Nettention.Proud.RmiID CG_RequestAttendancePackageReward = (Nettention.Proud.RmiID)15615;
		public const Nettention.Proud.RmiID CG_RequestAttendancePackageRewardAll = (Nettention.Proud.RmiID)15616;
		public const Nettention.Proud.RmiID CG_RequestMailADReward = (Nettention.Proud.RmiID)15617;
		public const Nettention.Proud.RmiID CG_RequestGambleShopBuy = (Nettention.Proud.RmiID)15651;
		public const Nettention.Proud.RmiID CG_RequestStepupGambleShopBuy = (Nettention.Proud.RmiID)15652;
		public const Nettention.Proud.RmiID CG_RequestStepupGambleMileageReward = (Nettention.Proud.RmiID)15653;
		public const Nettention.Proud.RmiID CG_RequestItemGambleShopInfo = (Nettention.Proud.RmiID)15654;
		public const Nettention.Proud.RmiID CG_RequestItemGambleShopBuy = (Nettention.Proud.RmiID)15655;
		public const Nettention.Proud.RmiID CG_RequestRandomShopBuy = (Nettention.Proud.RmiID)15656;
		public const Nettention.Proud.RmiID CG_RequestRandomShopRefresh = (Nettention.Proud.RmiID)15657;
		public const Nettention.Proud.RmiID CG_RequestRandomShopInfo = (Nettention.Proud.RmiID)15658;
		public const Nettention.Proud.RmiID CG_RequestBasePointShopInfo = (Nettention.Proud.RmiID)15659;
		public const Nettention.Proud.RmiID CG_RequestBasePointShopBuy = (Nettention.Proud.RmiID)15660;
		public const Nettention.Proud.RmiID CG_RequestBasePointShopReset = (Nettention.Proud.RmiID)15661;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpShopInfo = (Nettention.Proud.RmiID)15662;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpShopBuy = (Nettention.Proud.RmiID)15663;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpShopReset = (Nettention.Proud.RmiID)15664;
		public const Nettention.Proud.RmiID CG_RequestCoinShopInfo = (Nettention.Proud.RmiID)15665;
		public const Nettention.Proud.RmiID CG_RequestCoinShopBuy = (Nettention.Proud.RmiID)15666;
		public const Nettention.Proud.RmiID CG_RequestCoinShopDailyBuy = (Nettention.Proud.RmiID)15667;
		public const Nettention.Proud.RmiID CG_RequestCoinShopOnceBuy = (Nettention.Proud.RmiID)15668;
		public const Nettention.Proud.RmiID CG_RequestCostumeShopInfo = (Nettention.Proud.RmiID)15669;
		public const Nettention.Proud.RmiID CG_RequestCostumeShopBuy = (Nettention.Proud.RmiID)15670;
		public const Nettention.Proud.RmiID CG_RequestCostumeShopPackageBuy = (Nettention.Proud.RmiID)15671;
		public const Nettention.Proud.RmiID CG_RequestFriendPointShopInfo = (Nettention.Proud.RmiID)15672;
		public const Nettention.Proud.RmiID CG_RequestFriendPointShopBuy = (Nettention.Proud.RmiID)15673;
		public const Nettention.Proud.RmiID CG_RequestDiaShopInfo = (Nettention.Proud.RmiID)15674;
		public const Nettention.Proud.RmiID CG_RequestDiaShopBuy = (Nettention.Proud.RmiID)15675;
		public const Nettention.Proud.RmiID CG_RequestItemInventoryBuy = (Nettention.Proud.RmiID)15676;
		public const Nettention.Proud.RmiID CG_RequestWeaponInventoryBuy = (Nettention.Proud.RmiID)15677;
		public const Nettention.Proud.RmiID CG_RequestWeekStageKeyBuy = (Nettention.Proud.RmiID)15678;
		public const Nettention.Proud.RmiID CG_RequestCommonItemSell = (Nettention.Proud.RmiID)15679;
		public const Nettention.Proud.RmiID CG_RequestCommonItemRemove = (Nettention.Proud.RmiID)15680;
		public const Nettention.Proud.RmiID CG_RequestPackageBuy = (Nettention.Proud.RmiID)15681;
		public const Nettention.Proud.RmiID CG_RequestBuyDia = (Nettention.Proud.RmiID)15682;
		public const Nettention.Proud.RmiID CG_RequestBuyGold = (Nettention.Proud.RmiID)15683;
		public const Nettention.Proud.RmiID CG_RequestBuyStamina = (Nettention.Proud.RmiID)15684;
		public const Nettention.Proud.RmiID CG_RequestGuildShopInfo = (Nettention.Proud.RmiID)15685;
		public const Nettention.Proud.RmiID CG_RequestGuildShopBuy = (Nettention.Proud.RmiID)15686;
		public const Nettention.Proud.RmiID CG_RequestGuildShopReset = (Nettention.Proud.RmiID)15687;
		public const Nettention.Proud.RmiID CG_RequestFinalBossShopInfo = (Nettention.Proud.RmiID)15688;
		public const Nettention.Proud.RmiID CG_RequestFinalBossShopBuy = (Nettention.Proud.RmiID)15689;
		public const Nettention.Proud.RmiID CG_RequestEventCollaborationCoinShopInfo = (Nettention.Proud.RmiID)15690;
		public const Nettention.Proud.RmiID CG_RequestEventCollaborationCoinShopBuy = (Nettention.Proud.RmiID)15691;
		public const Nettention.Proud.RmiID CG_RequestBingoGambleShopInfo = (Nettention.Proud.RmiID)15692;
		public const Nettention.Proud.RmiID CG_RequestBingoGambleShopReset = (Nettention.Proud.RmiID)15693;
		public const Nettention.Proud.RmiID CG_RequestBingoGambleShopReward = (Nettention.Proud.RmiID)15694;
		public const Nettention.Proud.RmiID CG_RequestDiaShopPackageBuy = (Nettention.Proud.RmiID)15696;
		public const Nettention.Proud.RmiID CG_RequestRandomShopVisitReward = (Nettention.Proud.RmiID)15697;
		public const Nettention.Proud.RmiID CG_RequestGambleChoiceShopBuy = (Nettention.Proud.RmiID)15698;
		public const Nettention.Proud.RmiID CG_RequestRandomShopScheduleInfo = (Nettention.Proud.RmiID)15699;
		public const Nettention.Proud.RmiID CG_RequestPackageShopInfo = (Nettention.Proud.RmiID)15700;
		public const Nettention.Proud.RmiID CG_RequestFreePackageReward = (Nettention.Proud.RmiID)15701;
		public const Nettention.Proud.RmiID CG_RequestPackageMissionClose = (Nettention.Proud.RmiID)15702;
		public const Nettention.Proud.RmiID CG_RequestGambleShopInfo = (Nettention.Proud.RmiID)15703;
		public const Nettention.Proud.RmiID CG_RequestADRouletteReward = (Nettention.Proud.RmiID)15704;
		public const Nettention.Proud.RmiID CG_RequestQuestStart = (Nettention.Proud.RmiID)15801;
		public const Nettention.Proud.RmiID CG_RequestQuestProgress = (Nettention.Proud.RmiID)15802;
		public const Nettention.Proud.RmiID CG_RequestQuestClear = (Nettention.Proud.RmiID)15803;
		public const Nettention.Proud.RmiID CG_RequestQuestRemove = (Nettention.Proud.RmiID)15804;
		public const Nettention.Proud.RmiID CG_RequestNetmarbleQuestAchieve = (Nettention.Proud.RmiID)15805;
		public const Nettention.Proud.RmiID CG_RequestNetmarbleQuestReward = (Nettention.Proud.RmiID)15806;
		public const Nettention.Proud.RmiID CG_RequestDirectSelectorReward = (Nettention.Proud.RmiID)15807;
		public const Nettention.Proud.RmiID CG_RequestMissionProgress = (Nettention.Proud.RmiID)15808;
		public const Nettention.Proud.RmiID CG_RequestMissionClear = (Nettention.Proud.RmiID)15809;
		public const Nettention.Proud.RmiID CG_RequestMissionEventClear = (Nettention.Proud.RmiID)15810;
		public const Nettention.Proud.RmiID CG_RequestMissionGetAchievePointReward = (Nettention.Proud.RmiID)15811;
		public const Nettention.Proud.RmiID CG_RequestQuestChapterClear = (Nettention.Proud.RmiID)15812;
		public const Nettention.Proud.RmiID CG_RequestEventMissionGetAchievePointReward = (Nettention.Proud.RmiID)15813;
		public const Nettention.Proud.RmiID CG_RequestEventMissionCompleteReward = (Nettention.Proud.RmiID)15814;
		public const Nettention.Proud.RmiID CG_RequestEventMissionInfo = (Nettention.Proud.RmiID)15815;
		public const Nettention.Proud.RmiID CG_RequestEventQuestClear = (Nettention.Proud.RmiID)15816;
		public const Nettention.Proud.RmiID CG_RequestAnotherQuestClear = (Nettention.Proud.RmiID)15817;
		public const Nettention.Proud.RmiID CG_RequestQuestGuideListAllClearReward = (Nettention.Proud.RmiID)15818;
		public const Nettention.Proud.RmiID CG_RequestLobbyVRSearch = (Nettention.Proud.RmiID)15851;
		public const Nettention.Proud.RmiID CG_RequestLobbyVRHelbram = (Nettention.Proud.RmiID)15852;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcSkin = (Nettention.Proud.RmiID)15853;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcGift = (Nettention.Proud.RmiID)15854;
		public const Nettention.Proud.RmiID CG_RequestLobbyKingAmber = (Nettention.Proud.RmiID)15855;
		public const Nettention.Proud.RmiID CG_RequestLobbyDropInteractiveOpen = (Nettention.Proud.RmiID)15856;
		public const Nettention.Proud.RmiID CG_RequestLobbyUniqueInteractiveOpen = (Nettention.Proud.RmiID)15857;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcTalkInfo = (Nettention.Proud.RmiID)15858;
		public const Nettention.Proud.RmiID CG_RequestLobbyNpcTalkChoice = (Nettention.Proud.RmiID)15859;
		public const Nettention.Proud.RmiID CG_RequestLobbyBarrel = (Nettention.Proud.RmiID)15860;
		public const Nettention.Proud.RmiID CG_RequestLobbyBarrelRefill = (Nettention.Proud.RmiID)15861;
		public const Nettention.Proud.RmiID CG_RequestLobbyCleanTable = (Nettention.Proud.RmiID)15862;
		public const Nettention.Proud.RmiID CG_RequestLobbyServeBeer = (Nettention.Proud.RmiID)15863;
		public const Nettention.Proud.RmiID CG_RequestLobbyPlayJukebox = (Nettention.Proud.RmiID)15864;
		public const Nettention.Proud.RmiID CG_RequestLobbyElizabethTouch = (Nettention.Proud.RmiID)15865;
		public const Nettention.Proud.RmiID CG_RequestLobbyHawkAnger = (Nettention.Proud.RmiID)15866;
		public const Nettention.Proud.RmiID CG_RequestAttendanceReward = (Nettention.Proud.RmiID)15867;
		public const Nettention.Proud.RmiID CG_RequestAttendanceEventReward = (Nettention.Proud.RmiID)15868;
		public const Nettention.Proud.RmiID CG_RequestCookingStart = (Nettention.Proud.RmiID)15869;
		public const Nettention.Proud.RmiID CG_RequestRecipeActive = (Nettention.Proud.RmiID)15870;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeOrderInfo = (Nettention.Proud.RmiID)15871;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeOrder = (Nettention.Proud.RmiID)15872;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeDisorder = (Nettention.Proud.RmiID)15873;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeCollect = (Nettention.Proud.RmiID)15874;
		public const Nettention.Proud.RmiID CG_RequestCookingRecipeCollectOneSlot = (Nettention.Proud.RmiID)15875;
		public const Nettention.Proud.RmiID CG_RequestCookingUseCookingBuff = (Nettention.Proud.RmiID)15876;
		public const Nettention.Proud.RmiID CG_RequestGuestInfo = (Nettention.Proud.RmiID)15877;
		public const Nettention.Proud.RmiID CG_RequestGuestChange = (Nettention.Proud.RmiID)15878;
		public const Nettention.Proud.RmiID CG_RequestGuestChangeTarget = (Nettention.Proud.RmiID)15879;
		public const Nettention.Proud.RmiID CG_RequestGuestTalk = (Nettention.Proud.RmiID)15880;
		public const Nettention.Proud.RmiID CG_RequestGuestGift = (Nettention.Proud.RmiID)15881;
		public const Nettention.Proud.RmiID CG_RequestBirthdayNpcInfo = (Nettention.Proud.RmiID)15882;
		public const Nettention.Proud.RmiID CG_RequestRestReward = (Nettention.Proud.RmiID)15883;
		public const Nettention.Proud.RmiID CG_RequestLobbyHousingShopInfo = (Nettention.Proud.RmiID)15884;
		public const Nettention.Proud.RmiID CG_RequestLobbyHousingShopBuy = (Nettention.Proud.RmiID)15885;
		public const Nettention.Proud.RmiID CG_RequestLobbyFurnitureRegist = (Nettention.Proud.RmiID)15886;
		public const Nettention.Proud.RmiID CG_RequestUserMusicEdit = (Nettention.Proud.RmiID)15887;
		public const Nettention.Proud.RmiID CG_RequestAttendanceFortuneEventReward = (Nettention.Proud.RmiID)15888;
		public const Nettention.Proud.RmiID CG_RequestBasePointGoldDonation = (Nettention.Proud.RmiID)15901;
		public const Nettention.Proud.RmiID CG_RequestBasePointSetTrigger = (Nettention.Proud.RmiID)15902;
		public const Nettention.Proud.RmiID CG_RequestBasePointDropInteractiveOpen = (Nettention.Proud.RmiID)15903;
		public const Nettention.Proud.RmiID CG_RequestBasePointUniqueInteractiveOpen = (Nettention.Proud.RmiID)15904;
		public const Nettention.Proud.RmiID CG_RequestBasePointDailyReward = (Nettention.Proud.RmiID)15905;
		public const Nettention.Proud.RmiID CG_RequestBasePointDonationEventReward = (Nettention.Proud.RmiID)15906;
		public const Nettention.Proud.RmiID CG_RequestBasePointDonationInfo = (Nettention.Proud.RmiID)15907;
		public const Nettention.Proud.RmiID CG_RequestBasePointEventGoldDonation = (Nettention.Proud.RmiID)15908;
		public const Nettention.Proud.RmiID CG_RequestEventBasepointInfo = (Nettention.Proud.RmiID)15909;
		public const Nettention.Proud.RmiID CG_RequestDestroySetInviteOption = (Nettention.Proud.RmiID)15951;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetUserLoginList = (Nettention.Proud.RmiID)15952;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetFriendLoginList = (Nettention.Proud.RmiID)15953;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetGuildLoginList = (Nettention.Proud.RmiID)15954;
		public const Nettention.Proud.RmiID CG_RequestDestroyGetReceivedInvitationList = (Nettention.Proud.RmiID)15955;
		public const Nettention.Proud.RmiID CG_RequestDestroyInvite = (Nettention.Proud.RmiID)15956;
		public const Nettention.Proud.RmiID CG_RequestDestroyRemoveInvitation = (Nettention.Proud.RmiID)15957;
		public const Nettention.Proud.RmiID CG_RequestDestroyRemoveJoinInfo = (Nettention.Proud.RmiID)15958;
		public const Nettention.Proud.RmiID CG_RequestDestroyCreate = (Nettention.Proud.RmiID)15959;
		public const Nettention.Proud.RmiID CG_RequestDestroyJoin = (Nettention.Proud.RmiID)15960;
		public const Nettention.Proud.RmiID CG_RequestDestroyStart = (Nettention.Proud.RmiID)15961;
		public const Nettention.Proud.RmiID CG_RequestDestroyBattleStart = (Nettention.Proud.RmiID)15962;
		public const Nettention.Proud.RmiID CG_RequestDestroyClear = (Nettention.Proud.RmiID)15963;
		public const Nettention.Proud.RmiID CG_RequestDestroyReJoin = (Nettention.Proud.RmiID)15964;
		public const Nettention.Proud.RmiID CG_RequestDestroyRemove = (Nettention.Proud.RmiID)15965;
		public const Nettention.Proud.RmiID CG_RequestDestroyBattleEnd = (Nettention.Proud.RmiID)15966;
		public const Nettention.Proud.RmiID CG_RequestDestroyInviteAI = (Nettention.Proud.RmiID)15967;
		public const Nettention.Proud.RmiID CG_RequestDestroyKickOutAI = (Nettention.Proud.RmiID)15968;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyCreate = (Nettention.Proud.RmiID)15969;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyStart = (Nettention.Proud.RmiID)15970;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyClear = (Nettention.Proud.RmiID)15971;
		public const Nettention.Proud.RmiID CG_RequestEventDestroyRemove = (Nettention.Proud.RmiID)15972;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyCreate = (Nettention.Proud.RmiID)15973;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyStart = (Nettention.Proud.RmiID)15974;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyClear = (Nettention.Proud.RmiID)15975;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyPointRefresh = (Nettention.Proud.RmiID)15976;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyUserReward = (Nettention.Proud.RmiID)15977;
		public const Nettention.Proud.RmiID CG_RequestEventChallengeDestroyWorldReward = (Nettention.Proud.RmiID)15978;
		public const Nettention.Proud.RmiID CG_RequestFriendList = (Nettention.Proud.RmiID)16001;
		public const Nettention.Proud.RmiID CG_RequestFriendGuildInfo = (Nettention.Proud.RmiID)16002;
		public const Nettention.Proud.RmiID CG_RequestFriendApplySendList = (Nettention.Proud.RmiID)16003;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveList = (Nettention.Proud.RmiID)16004;
		public const Nettention.Proud.RmiID CG_RequestFriendApplySend = (Nettention.Proud.RmiID)16005;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReject = (Nettention.Proud.RmiID)16006;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveAccept = (Nettention.Proud.RmiID)16007;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveAcceptList = (Nettention.Proud.RmiID)16008;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveRefuse = (Nettention.Proud.RmiID)16009;
		public const Nettention.Proud.RmiID CG_RequestFriendApplyReceiveRefuseList = (Nettention.Proud.RmiID)16010;
		public const Nettention.Proud.RmiID CG_RequestFriendRemove = (Nettention.Proud.RmiID)16011;
		public const Nettention.Proud.RmiID CG_RequestFriendSearch = (Nettention.Proud.RmiID)16012;
		public const Nettention.Proud.RmiID CG_RequestFriendVisit = (Nettention.Proud.RmiID)16013;
		public const Nettention.Proud.RmiID CG_RequestFriendPointSend = (Nettention.Proud.RmiID)16014;
		public const Nettention.Proud.RmiID CG_RequestFriendPointSendAll = (Nettention.Proud.RmiID)16015;
		public const Nettention.Proud.RmiID CG_RequestFriendLobbyInfo = (Nettention.Proud.RmiID)16016;
		public const Nettention.Proud.RmiID CG_RequestFriendCookingRecipeInfo = (Nettention.Proud.RmiID)16017;
		public const Nettention.Proud.RmiID CG_RequestFriendCookingEat = (Nettention.Proud.RmiID)16018;
		public const Nettention.Proud.RmiID CG_RequestFriendCookingEatFriendList = (Nettention.Proud.RmiID)16019;
		public const Nettention.Proud.RmiID CG_RequestGuildRecommendList = (Nettention.Proud.RmiID)16051;
		public const Nettention.Proud.RmiID CG_RequestGuildInfoWithMemberList = (Nettention.Proud.RmiID)16052;
		public const Nettention.Proud.RmiID CG_RequestGuildSearchByName = (Nettention.Proud.RmiID)16053;
		public const Nettention.Proud.RmiID CG_RequestGuildCreate = (Nettention.Proud.RmiID)16054;
		public const Nettention.Proud.RmiID CG_RequestGuildDisband = (Nettention.Proud.RmiID)16055;
		public const Nettention.Proud.RmiID CG_RequestGuildApplicantList = (Nettention.Proud.RmiID)16056;
		public const Nettention.Proud.RmiID CG_RequestGuildApply = (Nettention.Proud.RmiID)16057;
		public const Nettention.Proud.RmiID CG_RequestGuildReturnApplication = (Nettention.Proud.RmiID)16058;
		public const Nettention.Proud.RmiID CG_RequestGuildAcceptApplicant = (Nettention.Proud.RmiID)16059;
		public const Nettention.Proud.RmiID CG_RequestGuildRejectApplicant = (Nettention.Proud.RmiID)16060;
		public const Nettention.Proud.RmiID CG_RequestGuildLevelUp = (Nettention.Proud.RmiID)16061;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeName = (Nettention.Proud.RmiID)16062;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeBoard = (Nettention.Proud.RmiID)16063;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeMaster = (Nettention.Proud.RmiID)16064;
		public const Nettention.Proud.RmiID CG_RequestGuildChangeMemberGrade = (Nettention.Proud.RmiID)16065;
		public const Nettention.Proud.RmiID CG_RequestGuildKickOutMember = (Nettention.Proud.RmiID)16066;
		public const Nettention.Proud.RmiID CG_RequestGuildLeave = (Nettention.Proud.RmiID)16067;
		public const Nettention.Proud.RmiID CG_RequestGuildRoomInfo = (Nettention.Proud.RmiID)16068;
		public const Nettention.Proud.RmiID CG_RequestGuildAttendance = (Nettention.Proud.RmiID)16069;
		public const Nettention.Proud.RmiID CG_RequestGuildAttendanceReward = (Nettention.Proud.RmiID)16070;
		public const Nettention.Proud.RmiID CG_RequestGuildUserInfo = (Nettention.Proud.RmiID)16071;
		public const Nettention.Proud.RmiID CG_RequestGuildAttendanceStatus = (Nettention.Proud.RmiID)16072;
		public const Nettention.Proud.RmiID CG_RequestGuildDonation = (Nettention.Proud.RmiID)16073;
		public const Nettention.Proud.RmiID CG_RequestGuildDonationInitialize = (Nettention.Proud.RmiID)16074;
		public const Nettention.Proud.RmiID CG_RequestGuildMissionInfo = (Nettention.Proud.RmiID)16075;
		public const Nettention.Proud.RmiID CG_RequestGuildMissionReward = (Nettention.Proud.RmiID)16076;
		public const Nettention.Proud.RmiID CG_RequestGuildDonationInfo = (Nettention.Proud.RmiID)16077;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillInfo = (Nettention.Proud.RmiID)16078;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillLevelUp = (Nettention.Proud.RmiID)16079;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillUse = (Nettention.Proud.RmiID)16080;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillDisuse = (Nettention.Proud.RmiID)16081;
		public const Nettention.Proud.RmiID CG_RequestGuildSkillUseInfo = (Nettention.Proud.RmiID)16082;
		public const Nettention.Proud.RmiID CG_RequestGuildMemberRankPointReward = (Nettention.Proud.RmiID)16083;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointRegister = (Nettention.Proud.RmiID)16084;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointMemeberRankList = (Nettention.Proud.RmiID)16085;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointGuildRankList = (Nettention.Proud.RmiID)16086;
		public const Nettention.Proud.RmiID CG_RequestGuildBattlePointUserRankList = (Nettention.Proud.RmiID)16087;
		public const Nettention.Proud.RmiID CG_RequestAPRechargeByUseItem = (Nettention.Proud.RmiID)16101;
		public const Nettention.Proud.RmiID CG_RequestWeekStageKeyOpen = (Nettention.Proud.RmiID)16102;
		public const Nettention.Proud.RmiID CG_RequestFoodBuffAutoUseOnOff = (Nettention.Proud.RmiID)16103;
		public const Nettention.Proud.RmiID CG_RequestItemUseRankExp = (Nettention.Proud.RmiID)16104;
		public const Nettention.Proud.RmiID CG_RequestItemUseBoxOpen = (Nettention.Proud.RmiID)16105;
		public const Nettention.Proud.RmiID CG_RequestItemUseRecipeExp = (Nettention.Proud.RmiID)16106;
		public const Nettention.Proud.RmiID CG_RequestItemUseWeeklyKeyBox = (Nettention.Proud.RmiID)16107;
		public const Nettention.Proud.RmiID CG_RequestItemUseWeaponTicket = (Nettention.Proud.RmiID)16108;
		public const Nettention.Proud.RmiID CG_RequestItemUseMusic = (Nettention.Proud.RmiID)16109;
		public const Nettention.Proud.RmiID CG_RequestTutorialAddStep = (Nettention.Proud.RmiID)16151;
		public const Nettention.Proud.RmiID CG_RequestTutorialSetFlag = (Nettention.Proud.RmiID)16152;
		public const Nettention.Proud.RmiID CG_RequestTutorialHeroFlag = (Nettention.Proud.RmiID)16153;
		public const Nettention.Proud.RmiID CG_RequestTutorialGambleShopBuy = (Nettention.Proud.RmiID)16154;
		public const Nettention.Proud.RmiID CG_RequestBattleTutorialInfo = (Nettention.Proud.RmiID)16155;
		public const Nettention.Proud.RmiID CG_RequestBattleTutorialSet = (Nettention.Proud.RmiID)16156;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchCreate = (Nettention.Proud.RmiID)16201;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchFriendList = (Nettention.Proud.RmiID)16202;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchInvite = (Nettention.Proud.RmiID)16203;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchReceivedInviteList = (Nettention.Proud.RmiID)16204;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchInviteAccept = (Nettention.Proud.RmiID)16205;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchInviteReject = (Nettention.Proud.RmiID)16206;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchStart = (Nettention.Proud.RmiID)16207;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchBattleStart = (Nettention.Proud.RmiID)16208;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchClear = (Nettention.Proud.RmiID)16209;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchExit = (Nettention.Proud.RmiID)16210;
		public const Nettention.Proud.RmiID CG_RequestFriendlyMatchSetInviteOption = (Nettention.Proud.RmiID)16211;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassInfo = (Nettention.Proud.RmiID)16251;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassRankUpReward = (Nettention.Proud.RmiID)16252;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassRankUpRewardAll = (Nettention.Proud.RmiID)16253;
		public const Nettention.Proud.RmiID CG_RequestEventSeasonPassRankBuy = (Nettention.Proud.RmiID)16254;
		public const Nettention.Proud.RmiID CG_RequestWestSideServerInfo_Random = (Nettention.Proud.RmiID)16301;
		public const Nettention.Proud.RmiID CG_RequestWestSideServerInfo_Fixed = (Nettention.Proud.RmiID)16302;
		public const Nettention.Proud.RmiID CG_RequestWestSideServerInfo_Recommand = (Nettention.Proud.RmiID)16303;
		public const Nettention.Proud.RmiID CG_RequestWestSide_PlayerInfo = (Nettention.Proud.RmiID)16304;
		public const Nettention.Proud.RmiID CG_RequestWestSide_PlayerteamInfo = (Nettention.Proud.RmiID)16305;
		public const Nettention.Proud.RmiID CG_RequestWestSide_PlayerGuildInfo = (Nettention.Proud.RmiID)16306;
		public const Nettention.Proud.RmiID CG_RequestWorldChattingChannel = (Nettention.Proud.RmiID)16307;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLobbyInfo = (Nettention.Proud.RmiID)16351;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpJoin = (Nettention.Proud.RmiID)16352;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpTopRankerList = (Nettention.Proud.RmiID)16353;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLastRankerList = (Nettention.Proud.RmiID)16354;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpMatching = (Nettention.Proud.RmiID)16355;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpBattleStart = (Nettention.Proud.RmiID)16356;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpBattleEnd = (Nettention.Proud.RmiID)16357;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpRollback = (Nettention.Proud.RmiID)16358;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpIngameBattleStart = (Nettention.Proud.RmiID)16359;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerLobbyInfo = (Nettention.Proud.RmiID)16360;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerJoin = (Nettention.Proud.RmiID)16361;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerTopRankerList = (Nettention.Proud.RmiID)16362;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerMatching = (Nettention.Proud.RmiID)16363;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerBattleStart = (Nettention.Proud.RmiID)16364;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerBattleEnd = (Nettention.Proud.RmiID)16365;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpAllInfo = (Nettention.Proud.RmiID)16366;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLastRankerBattleInfo = (Nettention.Proud.RmiID)16367;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLastRankerBattleStart = (Nettention.Proud.RmiID)16368;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerRollback = (Nettention.Proud.RmiID)16369;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimePvpLowerIngameBattleStart = (Nettention.Proud.RmiID)16370;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionLobbyInfo = (Nettention.Proud.RmiID)16371;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionJoin = (Nettention.Proud.RmiID)16372;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionTopRankerList = (Nettention.Proud.RmiID)16373;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionMatching = (Nettention.Proud.RmiID)16374;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionBattleEnd = (Nettention.Proud.RmiID)16375;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionIngameBattleStart = (Nettention.Proud.RmiID)16376;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionHistory = (Nettention.Proud.RmiID)16377;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionChangeMatchingList = (Nettention.Proud.RmiID)16378;
		public const Nettention.Proud.RmiID CG_RequestArenaRealTimeDecisionMatchingSimpleInfo = (Nettention.Proud.RmiID)16379;
		public const Nettention.Proud.RmiID CG_RequestPvpSeasonInfo = (Nettention.Proud.RmiID)16400;
		public const Nettention.Proud.RmiID CG_RequestPvpSeasonHistory = (Nettention.Proud.RmiID)16401;
		public const Nettention.Proud.RmiID CG_RequestBossWarCreate = (Nettention.Proud.RmiID)16900;
		public const Nettention.Proud.RmiID CG_RequestBossWarJoin = (Nettention.Proud.RmiID)16901;
		public const Nettention.Proud.RmiID CG_RequestBossWarStart = (Nettention.Proud.RmiID)16902;
		public const Nettention.Proud.RmiID CG_RequestBossWarOnlineFriendList = (Nettention.Proud.RmiID)16903;
		public const Nettention.Proud.RmiID CG_RequestBossWarOnlineGuildMemberList = (Nettention.Proud.RmiID)16904;
		public const Nettention.Proud.RmiID CG_RequestBossWarOnlineUserRankRangeList = (Nettention.Proud.RmiID)16905;
		public const Nettention.Proud.RmiID CG_RequestBossWarInvitationReceiveList = (Nettention.Proud.RmiID)16906;
		public const Nettention.Proud.RmiID CG_RequestBossWarRemoveInvitation = (Nettention.Proud.RmiID)16907;
		public const Nettention.Proud.RmiID CG_RequestBossWarInvite = (Nettention.Proud.RmiID)16908;
		public const Nettention.Proud.RmiID CG_RequestBossWarKickOut = (Nettention.Proud.RmiID)16909;
		public const Nettention.Proud.RmiID CG_RequestBossWarReady = (Nettention.Proud.RmiID)16910;
		public const Nettention.Proud.RmiID CG_RequestBossWarReturnReady = (Nettention.Proud.RmiID)16911;
		public const Nettention.Proud.RmiID CG_RequestBossWarLeave = (Nettention.Proud.RmiID)16912;
		public const Nettention.Proud.RmiID CG_RequestBossWarBattleStart = (Nettention.Proud.RmiID)16913;
		public const Nettention.Proud.RmiID CG_RequestBossWarBattleSync = (Nettention.Proud.RmiID)16914;
		public const Nettention.Proud.RmiID CG_RequestBossWarBattleEnd = (Nettention.Proud.RmiID)16915;
		public const Nettention.Proud.RmiID CG_RequestBossWarReward = (Nettention.Proud.RmiID)16916;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeInfo = (Nettention.Proud.RmiID)16501;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeBoxGachaInfo = (Nettention.Proud.RmiID)16502;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeBoxGachaPickup = (Nettention.Proud.RmiID)16503;
		public const Nettention.Proud.RmiID CG_RequestEventExchangeBoxGachaReset = (Nettention.Proud.RmiID)16504;
		public const Nettention.Proud.RmiID CG_RequestEventPaybackReward = (Nettention.Proud.RmiID)16511;
		public const Nettention.Proud.RmiID CG_RequestEventSnsShareProgress = (Nettention.Proud.RmiID)16512;
		public const Nettention.Proud.RmiID CG_RequestEventSnsShareReward = (Nettention.Proud.RmiID)16513;
		public const Nettention.Proud.RmiID CG_RequestGagueEventInfo = (Nettention.Proud.RmiID)16521;
		public const Nettention.Proud.RmiID CG_RequestGagueEventCharge = (Nettention.Proud.RmiID)16522;
		public const Nettention.Proud.RmiID CG_RequestGagueEventReward = (Nettention.Proud.RmiID)16523;
		public const Nettention.Proud.RmiID CG_RequestGagueEventReset = (Nettention.Proud.RmiID)16524;
		public const Nettention.Proud.RmiID CG_RequestEventLadderReward = (Nettention.Proud.RmiID)16531;
		public const Nettention.Proud.RmiID CG_RequestEventLobbyGiftReward = (Nettention.Proud.RmiID)16532;
		public const Nettention.Proud.RmiID CG_RequestEventTimeMissionInfo = (Nettention.Proud.RmiID)16541;
		public const Nettention.Proud.RmiID CG_RequestEventTimeMissionStart = (Nettention.Proud.RmiID)16542;
		public const Nettention.Proud.RmiID CG_RequestEventLobbyDecorationReward = (Nettention.Proud.RmiID)16550;
		public const Nettention.Proud.RmiID CG_RequestRegistPlayTitle = (Nettention.Proud.RmiID)16801;
		public const Nettention.Proud.RmiID CG_RequestPlayTitleMissionReward = (Nettention.Proud.RmiID)16802;
		public const Nettention.Proud.RmiID CG_RequestTournamentList = (Nettention.Proud.RmiID)16811;
		public const Nettention.Proud.RmiID CG_RequestTournamentProgressInfo = (Nettention.Proud.RmiID)16812;
		public const Nettention.Proud.RmiID CG_RequestTournamentResultInfo = (Nettention.Proud.RmiID)16813;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchJoin = (Nettention.Proud.RmiID)16814;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchBattleStart = (Nettention.Proud.RmiID)16816;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchBattleEnd = (Nettention.Proud.RmiID)16817;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchExit = (Nettention.Proud.RmiID)16818;
		public const Nettention.Proud.RmiID CG_RequestTournamentReward = (Nettention.Proud.RmiID)16819;
		public const Nettention.Proud.RmiID CG_RequestTournamentPlayerTeamSlotChange = (Nettention.Proud.RmiID)16820;
		public const Nettention.Proud.RmiID CG_RequestTournamentPlayerTeamInfo = (Nettention.Proud.RmiID)16821;
		public const Nettention.Proud.RmiID CG_RequestTournamentCheer = (Nettention.Proud.RmiID)16822;
		public const Nettention.Proud.RmiID CG_RequestTournamentCheerList = (Nettention.Proud.RmiID)16823;
		public const Nettention.Proud.RmiID CG_RequestTournamentWatcherJoin = (Nettention.Proud.RmiID)16824;
		public const Nettention.Proud.RmiID CG_RequestTournamentWatcherExit = (Nettention.Proud.RmiID)16825;
		public const Nettention.Proud.RmiID CG_RequestTournamentMatchPlayInfo = (Nettention.Proud.RmiID)16826;
		public const Nettention.Proud.RmiID CG_RequestTournamentReplayInfo = (Nettention.Proud.RmiID)16827;
		public const Nettention.Proud.RmiID CG_RequestGuildWarLobbyInfo = (Nettention.Proud.RmiID)17000;
		public const Nettention.Proud.RmiID CG_RequestGuildWarRankInfo = (Nettention.Proud.RmiID)17001;
		public const Nettention.Proud.RmiID CG_RequestGuildWarVersusRecordInfo = (Nettention.Proud.RmiID)17002;
		public const Nettention.Proud.RmiID CG_RequestGuildWarGuildMemberList = (Nettention.Proud.RmiID)17003;
		public const Nettention.Proud.RmiID CG_RequestGuildWarWorldMapInfo = (Nettention.Proud.RmiID)17004;
		public const Nettention.Proud.RmiID CG_RequestGuildWarAttackSquadChange = (Nettention.Proud.RmiID)17005;
		public const Nettention.Proud.RmiID CG_RequestGuildWarDefenceTeamChange = (Nettention.Proud.RmiID)17006;
		public const Nettention.Proud.RmiID CG_RequestGuildWarRegionBonusScoreChange = (Nettention.Proud.RmiID)17007;
		public const Nettention.Proud.RmiID CG_RequestGuildWarAreaGuildMemberChange = (Nettention.Proud.RmiID)17008;
		public const Nettention.Proud.RmiID CG_RequestGuildWarBattleRecordInfo = (Nettention.Proud.RmiID)17009;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_Start = (Nettention.Proud.RmiID)17010;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_Clear = (Nettention.Proud.RmiID)17011;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_Rejoin = (Nettention.Proud.RmiID)17012;
		public const Nettention.Proud.RmiID CG_Request_GuildWar_Stage_HeroStatus_Sync = (Nettention.Proud.RmiID)17013;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			CG_RequestChannelUserInfo,
			CG_RequestHeartBeat,
			CG_RequestChangeNickname,
			CG_RequestChangeWantToSay,
			CG_RequestTeamInfo,
			CG_RequestTeamSlotChange,
			CG_RequestTeamNameChange,
			CG_RequestLobbyInfo,
			CG_RequestBasePointInfo,
			CG_RequestMercenaryList,
			CG_RequestMercenaryInfo,
			CG_RequestGuildInfo,
			CG_RequestChatStampUpdateBookmark,
			CG_RequestChatStampUpdateQuickMessage,
			CG_RequestMainSkinChange,
			CG_RequestEventList,
			CG_RequestCheatEnter,
			CG_RequestCheatStageClear,
			CG_RequestDllGetItem,
			CG_RequestRecommendFriendUSNList,
			CG_RequestDailyReset,
			CG_RequestFrozenAssetRedeem,
			CG_RequestSecurityToken,
			CG_RequestNetmarbleAuth,
			CG_RequestAuthenticateCreate,
			CG_RequestEditorUserInfoByNickName,
			CG_RequestLogin,
			CG_RequestLoginInstantly,
			CG_RetryRequest,
			CG_RequestBillingInitialize,
			CG_RequestBillingVerifyPU,
			CG_RequestBillingRemainTR,
			CG_RequestBillingCouponVerify,
			CG_RequestBillingCrossPromotion,
			CG_RequestBillingPackageShop,
			CG_RequestAgeInput,
			CG_RequestSDKInfoChange,
			CG_RequestSkinLevelUpBySkinMaterial,
			CG_RequestSkinResearch,
			CG_RequestSkinResearchInit,
			CG_RequestSkinMaterialGrind,
			CG_RequestSkinAwaken,
			CG_RequestSkinHeadStyleChange,
			CG_RequestSkinEvolution,
			CG_RequestSkinSkillLevelUp,
			CG_RequestSkinGiveFellowshipExp,
			CG_RequestSkinFellowshipLevelUpReward,
			CG_RequestCostumeEquip,
			CG_RequestCostumeUnEquip,
			CG_RequestCostumeUnLock,
			CG_RequestSkinOverEvolution,
			CG_RequestSkinMaxAwakenReward,
			CG_RequestCostumeRegister,
			CG_RequestSkinLoveReward,
			CG_RequestCostumeAutoRegister,
			CG_RequestStoryCostume,
			CG_RequestCostumeLevelUp,
			CG_RequestSkinMaxAwaken,
			CG_RequestWeaponEquip,
			CG_RequestWeaponUnEquip,
			CG_RequestWeaponSell,
			CG_RequestWeaponGrind,
			CG_RequestWeaponUpgrade,
			CG_RequestWeaponUpgradeRetry,
			CG_RequestWeaponEvolution,
			CG_RequestWeaponEvolutionRetry,
			CG_RequestWeaponOptionEnhance,
			CG_RequestWeaponLock,
			CG_RequestWeaponUnLock,
			CG_RequestWeaponEquipExchange,
			CG_RequestWeaponEquipExchangeAll,
			CG_RequestWeaponEquipRecommand,
			CG_RequestWeaponCarve,
			CG_RequestWeaponCarveRemove,
			CG_RequestStageInfo,
			CG_RequestStageRejoin,
			CG_Request_Week_Stage_Start,
			CG_Request_Week_Stage_Clear,
			CG_Request_Week_Stage_Continue,
			CG_Request_Main_Stage_Start,
			CG_Request_Main_Stage_Clear,
			CG_Request_Main_Stage_Continue,
			CG_Request_Free_Stage_Start,
			CG_Request_Free_Stage_Clear,
			CG_Request_Free_Stage_Continue,
			CG_RequestHawkRunStageStart,
			CG_RequestHawkRunStageClear,
			CG_RequestEventStageClear,
			CG_Request_Quest_Stage_Start,
			CG_Request_Quest_Stage_Clear,
			CG_Request_Quest_Stage_Continue,
			CG_Request_Boss_Stage_Start,
			CG_Request_Boss_Stage_Clear,
			CG_Request_Boss_Stage_Continue,
			CG_Request_Memorial_Stage_Start,
			CG_Request_Memorial_Stage_Clear,
			CG_Request_Memorial_Stage_Continue,
			CG_Request_Limited_Stage_Start,
			CG_Request_Limited_Stage_Clear,
			CG_Request_Limited_Stage_Continue,
			CG_Request_Main_ExtraStage_Start,
			CG_Request_Main_ExtraStage_Clear,
			CG_Request_Main_ExtraStage_Continue,
			CG_Request_Boss_ExtraStage_Start,
			CG_Request_Boss_ExtraStage_Clear,
			CG_Request_Boss_ExtraStage_Continue,
			CG_RequestRewardStageClear,
			CG_Request_SingleSiege_ExtraStage_Start,
			CG_Request_SingleSiege_ExtraStage_Clear,
			CG_Request_SingleSiege_ExtraStage_Continue,
			CG_Request_FinalBoss_Stage_Start,
			CG_Request_FinalBoss_Stage_Clear,
			CG_Request_FinalBoss_Stage_Continue,
			CG_Request_FinalBoss_Season_Info,
			CG_Request_Training_Stage_Info,
			CG_Request_Training_Stage_Start,
			CG_Request_Training_Stage_Clear,
			CG_Request_Training_Stage_Continue,
			CG_Request_Training_Stage_Open,
			CG_Request_Training_Stage_Refresh,
			CG_Request_GuildBoss_Stage_Start,
			CG_Request_GuildBoss_Stage_Clear,
			CG_Request_GuildBoss_Lobby_Info,
			CG_Request_GuildBoss_Rank_Info,
			CG_Request_GuildBoss_LastWeek_Rank_Info,
			CG_Request_GuildBoss_Time_Refresh,
			CG_Request_AnotherMain_Stage_Start,
			CG_Request_AnotherMain_Stage_Clear,
			CG_Request_AnotherMain_Stage_Continue,
			CG_Request_FinalBoss_Season_Rank_Info,
			CG_Request_Reverse_Stage_Start,
			CG_Request_Reverse_Stage_Clear,
			CG_Request_Reverse_Star_Reward,
			CG_Request_Reverse_Group_Reward,
			CG_Request_Main_EventAreaStage_Start,
			CG_Request_Main_EventAreaStage_Clear,
			CG_Request_Main_EventAreaStage_Continue,
			CG_Request_Free_EventAreaStage_Start,
			CG_Request_Free_EventAreaStage_Clear,
			CG_Request_Free_EventAreaStage_Continue,
			CG_RequestEventAreaRewardStageClear,
			CG_Request_Free_EventStage_Start,
			CG_Request_Free_EventStage_Clear,
			CG_Request_Free_EventStage_Continue,
			CG_RequestEventExchange,
			CG_RequestEventPlayCountReward,
			CG_Request_Main_ListEventStage_Start,
			CG_Request_Main_ListEventStage_Clear,
			CG_Request_Main_ListEventStage_Continue,
			CG_Request_Free_ListEventStage_Start,
			CG_Request_Free_ListEventStage_Clear,
			CG_Request_Free_ListEventStage_Continue,
			CG_Request_Main_FinalBossStage_Start,
			CG_Request_Main_FinalBossStage_Clear,
			CG_Request_Main_FinalBossStage_Continue,
			CG_Request_FinalBoss_EventFreeStage_Start,
			CG_Request_FinalBoss_EventFreeStage_Clear,
			CG_Request_FinalBoss_EventFreeStage_Continue,
			CG_Request_Limited_EventStage_Start,
			CG_Request_Limited_EventStage_Clear,
			CG_Request_Limited_EventStage_Continue,
			CG_Request_Boss_EventStage_Start,
			CG_Request_Boss_EventStage_Clear,
			CG_Request_Boss_EventStage_Continue,
			CG_Request_Monthly_EventStage_Start,
			CG_Request_Monthly_EventStage_Clear,
			CG_Request_Monthly_EventStage_Continue,
			CG_RequestMonthlyStagePointReward,
			CG_RequestWeekStageGaugeReward,
			CG_RequestIngameBattleStart,
			CG_RequestStageEndLog,
			CG_Request_ChallengeBoss_EventStage_Start,
			CG_Request_ChallengeBoss_EventStage_Clear,
			CG_Request_ChallengeBoss_EventStage_Continue,
			CG_Request_ChallengeBoss_EventStage_Info,
			CG_Request_ChallengeBoss_Event_Point_Reward,
			CG_RequestMailList,
			CG_RequestMailConfirm,
			CG_RequestMailConfirmAll,
			CG_RequestMailHistoryList,
			CG_RequestMailRecentlyHistoryList,
			CG_RequestFriendMailList,
			CG_RequestFriendMailConfirm,
			CG_RequestFriendMailConfirmAll,
			CG_RequestNoticeMailReward,
			CG_RequestPackageMailList,
			CG_RequestPackageMailGet,
			CG_RequestPackageMailHistoryList,
			CG_RequestLevelUpPackageReward,
			CG_RequestLevelUpPackageRewardAll,
			CG_RequestAttendancePackageReward,
			CG_RequestAttendancePackageRewardAll,
			CG_RequestMailADReward,
			CG_RequestGambleShopBuy,
			CG_RequestStepupGambleShopBuy,
			CG_RequestStepupGambleMileageReward,
			CG_RequestItemGambleShopInfo,
			CG_RequestItemGambleShopBuy,
			CG_RequestRandomShopBuy,
			CG_RequestRandomShopRefresh,
			CG_RequestRandomShopInfo,
			CG_RequestBasePointShopInfo,
			CG_RequestBasePointShopBuy,
			CG_RequestBasePointShopReset,
			CG_RequestArenaRealTimePvpShopInfo,
			CG_RequestArenaRealTimePvpShopBuy,
			CG_RequestArenaRealTimePvpShopReset,
			CG_RequestCoinShopInfo,
			CG_RequestCoinShopBuy,
			CG_RequestCoinShopDailyBuy,
			CG_RequestCoinShopOnceBuy,
			CG_RequestCostumeShopInfo,
			CG_RequestCostumeShopBuy,
			CG_RequestCostumeShopPackageBuy,
			CG_RequestFriendPointShopInfo,
			CG_RequestFriendPointShopBuy,
			CG_RequestDiaShopInfo,
			CG_RequestDiaShopBuy,
			CG_RequestItemInventoryBuy,
			CG_RequestWeaponInventoryBuy,
			CG_RequestWeekStageKeyBuy,
			CG_RequestCommonItemSell,
			CG_RequestCommonItemRemove,
			CG_RequestPackageBuy,
			CG_RequestBuyDia,
			CG_RequestBuyGold,
			CG_RequestBuyStamina,
			CG_RequestGuildShopInfo,
			CG_RequestGuildShopBuy,
			CG_RequestGuildShopReset,
			CG_RequestFinalBossShopInfo,
			CG_RequestFinalBossShopBuy,
			CG_RequestEventCollaborationCoinShopInfo,
			CG_RequestEventCollaborationCoinShopBuy,
			CG_RequestBingoGambleShopInfo,
			CG_RequestBingoGambleShopReset,
			CG_RequestBingoGambleShopReward,
			CG_RequestDiaShopPackageBuy,
			CG_RequestRandomShopVisitReward,
			CG_RequestGambleChoiceShopBuy,
			CG_RequestRandomShopScheduleInfo,
			CG_RequestPackageShopInfo,
			CG_RequestFreePackageReward,
			CG_RequestPackageMissionClose,
			CG_RequestGambleShopInfo,
			CG_RequestADRouletteReward,
			CG_RequestQuestStart,
			CG_RequestQuestProgress,
			CG_RequestQuestClear,
			CG_RequestQuestRemove,
			CG_RequestNetmarbleQuestAchieve,
			CG_RequestNetmarbleQuestReward,
			CG_RequestDirectSelectorReward,
			CG_RequestMissionProgress,
			CG_RequestMissionClear,
			CG_RequestMissionEventClear,
			CG_RequestMissionGetAchievePointReward,
			CG_RequestQuestChapterClear,
			CG_RequestEventMissionGetAchievePointReward,
			CG_RequestEventMissionCompleteReward,
			CG_RequestEventMissionInfo,
			CG_RequestEventQuestClear,
			CG_RequestAnotherQuestClear,
			CG_RequestQuestGuideListAllClearReward,
			CG_RequestLobbyVRSearch,
			CG_RequestLobbyVRHelbram,
			CG_RequestLobbyNpcSkin,
			CG_RequestLobbyNpcGift,
			CG_RequestLobbyKingAmber,
			CG_RequestLobbyDropInteractiveOpen,
			CG_RequestLobbyUniqueInteractiveOpen,
			CG_RequestLobbyNpcTalkInfo,
			CG_RequestLobbyNpcTalkChoice,
			CG_RequestLobbyBarrel,
			CG_RequestLobbyBarrelRefill,
			CG_RequestLobbyCleanTable,
			CG_RequestLobbyServeBeer,
			CG_RequestLobbyPlayJukebox,
			CG_RequestLobbyElizabethTouch,
			CG_RequestLobbyHawkAnger,
			CG_RequestAttendanceReward,
			CG_RequestAttendanceEventReward,
			CG_RequestCookingStart,
			CG_RequestRecipeActive,
			CG_RequestCookingRecipeOrderInfo,
			CG_RequestCookingRecipeOrder,
			CG_RequestCookingRecipeDisorder,
			CG_RequestCookingRecipeCollect,
			CG_RequestCookingRecipeCollectOneSlot,
			CG_RequestCookingUseCookingBuff,
			CG_RequestGuestInfo,
			CG_RequestGuestChange,
			CG_RequestGuestChangeTarget,
			CG_RequestGuestTalk,
			CG_RequestGuestGift,
			CG_RequestBirthdayNpcInfo,
			CG_RequestRestReward,
			CG_RequestLobbyHousingShopInfo,
			CG_RequestLobbyHousingShopBuy,
			CG_RequestLobbyFurnitureRegist,
			CG_RequestUserMusicEdit,
			CG_RequestAttendanceFortuneEventReward,
			CG_RequestBasePointGoldDonation,
			CG_RequestBasePointSetTrigger,
			CG_RequestBasePointDropInteractiveOpen,
			CG_RequestBasePointUniqueInteractiveOpen,
			CG_RequestBasePointDailyReward,
			CG_RequestBasePointDonationEventReward,
			CG_RequestBasePointDonationInfo,
			CG_RequestBasePointEventGoldDonation,
			CG_RequestEventBasepointInfo,
			CG_RequestDestroySetInviteOption,
			CG_RequestDestroyGetUserLoginList,
			CG_RequestDestroyGetFriendLoginList,
			CG_RequestDestroyGetGuildLoginList,
			CG_RequestDestroyGetReceivedInvitationList,
			CG_RequestDestroyInvite,
			CG_RequestDestroyRemoveInvitation,
			CG_RequestDestroyRemoveJoinInfo,
			CG_RequestDestroyCreate,
			CG_RequestDestroyJoin,
			CG_RequestDestroyStart,
			CG_RequestDestroyBattleStart,
			CG_RequestDestroyClear,
			CG_RequestDestroyReJoin,
			CG_RequestDestroyRemove,
			CG_RequestDestroyBattleEnd,
			CG_RequestDestroyInviteAI,
			CG_RequestDestroyKickOutAI,
			CG_RequestEventDestroyCreate,
			CG_RequestEventDestroyStart,
			CG_RequestEventDestroyClear,
			CG_RequestEventDestroyRemove,
			CG_RequestEventChallengeDestroyCreate,
			CG_RequestEventChallengeDestroyStart,
			CG_RequestEventChallengeDestroyClear,
			CG_RequestEventChallengeDestroyPointRefresh,
			CG_RequestEventChallengeDestroyUserReward,
			CG_RequestEventChallengeDestroyWorldReward,
			CG_RequestFriendList,
			CG_RequestFriendGuildInfo,
			CG_RequestFriendApplySendList,
			CG_RequestFriendApplyReceiveList,
			CG_RequestFriendApplySend,
			CG_RequestFriendApplyReject,
			CG_RequestFriendApplyReceiveAccept,
			CG_RequestFriendApplyReceiveAcceptList,
			CG_RequestFriendApplyReceiveRefuse,
			CG_RequestFriendApplyReceiveRefuseList,
			CG_RequestFriendRemove,
			CG_RequestFriendSearch,
			CG_RequestFriendVisit,
			CG_RequestFriendPointSend,
			CG_RequestFriendPointSendAll,
			CG_RequestFriendLobbyInfo,
			CG_RequestFriendCookingRecipeInfo,
			CG_RequestFriendCookingEat,
			CG_RequestFriendCookingEatFriendList,
			CG_RequestGuildRecommendList,
			CG_RequestGuildInfoWithMemberList,
			CG_RequestGuildSearchByName,
			CG_RequestGuildCreate,
			CG_RequestGuildDisband,
			CG_RequestGuildApplicantList,
			CG_RequestGuildApply,
			CG_RequestGuildReturnApplication,
			CG_RequestGuildAcceptApplicant,
			CG_RequestGuildRejectApplicant,
			CG_RequestGuildLevelUp,
			CG_RequestGuildChangeName,
			CG_RequestGuildChangeBoard,
			CG_RequestGuildChangeMaster,
			CG_RequestGuildChangeMemberGrade,
			CG_RequestGuildKickOutMember,
			CG_RequestGuildLeave,
			CG_RequestGuildRoomInfo,
			CG_RequestGuildAttendance,
			CG_RequestGuildAttendanceReward,
			CG_RequestGuildUserInfo,
			CG_RequestGuildAttendanceStatus,
			CG_RequestGuildDonation,
			CG_RequestGuildDonationInitialize,
			CG_RequestGuildMissionInfo,
			CG_RequestGuildMissionReward,
			CG_RequestGuildDonationInfo,
			CG_RequestGuildSkillInfo,
			CG_RequestGuildSkillLevelUp,
			CG_RequestGuildSkillUse,
			CG_RequestGuildSkillDisuse,
			CG_RequestGuildSkillUseInfo,
			CG_RequestGuildMemberRankPointReward,
			CG_RequestGuildBattlePointRegister,
			CG_RequestGuildBattlePointMemeberRankList,
			CG_RequestGuildBattlePointGuildRankList,
			CG_RequestGuildBattlePointUserRankList,
			CG_RequestAPRechargeByUseItem,
			CG_RequestWeekStageKeyOpen,
			CG_RequestFoodBuffAutoUseOnOff,
			CG_RequestItemUseRankExp,
			CG_RequestItemUseBoxOpen,
			CG_RequestItemUseRecipeExp,
			CG_RequestItemUseWeeklyKeyBox,
			CG_RequestItemUseWeaponTicket,
			CG_RequestItemUseMusic,
			CG_RequestTutorialAddStep,
			CG_RequestTutorialSetFlag,
			CG_RequestTutorialHeroFlag,
			CG_RequestTutorialGambleShopBuy,
			CG_RequestBattleTutorialInfo,
			CG_RequestBattleTutorialSet,
			CG_RequestFriendlyMatchCreate,
			CG_RequestFriendlyMatchFriendList,
			CG_RequestFriendlyMatchInvite,
			CG_RequestFriendlyMatchReceivedInviteList,
			CG_RequestFriendlyMatchInviteAccept,
			CG_RequestFriendlyMatchInviteReject,
			CG_RequestFriendlyMatchStart,
			CG_RequestFriendlyMatchBattleStart,
			CG_RequestFriendlyMatchClear,
			CG_RequestFriendlyMatchExit,
			CG_RequestFriendlyMatchSetInviteOption,
			CG_RequestEventSeasonPassInfo,
			CG_RequestEventSeasonPassRankUpReward,
			CG_RequestEventSeasonPassRankUpRewardAll,
			CG_RequestEventSeasonPassRankBuy,
			CG_RequestWestSideServerInfo_Random,
			CG_RequestWestSideServerInfo_Fixed,
			CG_RequestWestSideServerInfo_Recommand,
			CG_RequestWestSide_PlayerInfo,
			CG_RequestWestSide_PlayerteamInfo,
			CG_RequestWestSide_PlayerGuildInfo,
			CG_RequestWorldChattingChannel,
			CG_RequestArenaRealTimePvpLobbyInfo,
			CG_RequestArenaRealTimePvpJoin,
			CG_RequestArenaRealTimePvpTopRankerList,
			CG_RequestArenaRealTimePvpLastRankerList,
			CG_RequestArenaRealTimePvpMatching,
			CG_RequestArenaRealTimePvpBattleStart,
			CG_RequestArenaRealTimePvpBattleEnd,
			CG_RequestArenaRealTimePvpRollback,
			CG_RequestArenaRealTimePvpIngameBattleStart,
			CG_RequestArenaRealTimePvpLowerLobbyInfo,
			CG_RequestArenaRealTimePvpLowerJoin,
			CG_RequestArenaRealTimePvpLowerTopRankerList,
			CG_RequestArenaRealTimePvpLowerMatching,
			CG_RequestArenaRealTimePvpLowerBattleStart,
			CG_RequestArenaRealTimePvpLowerBattleEnd,
			CG_RequestArenaRealTimePvpAllInfo,
			CG_RequestArenaRealTimePvpLastRankerBattleInfo,
			CG_RequestArenaRealTimePvpLastRankerBattleStart,
			CG_RequestArenaRealTimePvpLowerRollback,
			CG_RequestArenaRealTimePvpLowerIngameBattleStart,
			CG_RequestArenaRealTimeDecisionLobbyInfo,
			CG_RequestArenaRealTimeDecisionJoin,
			CG_RequestArenaRealTimeDecisionTopRankerList,
			CG_RequestArenaRealTimeDecisionMatching,
			CG_RequestArenaRealTimeDecisionBattleEnd,
			CG_RequestArenaRealTimeDecisionIngameBattleStart,
			CG_RequestArenaRealTimeDecisionHistory,
			CG_RequestArenaRealTimeDecisionChangeMatchingList,
			CG_RequestArenaRealTimeDecisionMatchingSimpleInfo,
			CG_RequestPvpSeasonInfo,
			CG_RequestPvpSeasonHistory,
			CG_RequestBossWarCreate,
			CG_RequestBossWarJoin,
			CG_RequestBossWarStart,
			CG_RequestBossWarOnlineFriendList,
			CG_RequestBossWarOnlineGuildMemberList,
			CG_RequestBossWarOnlineUserRankRangeList,
			CG_RequestBossWarInvitationReceiveList,
			CG_RequestBossWarRemoveInvitation,
			CG_RequestBossWarInvite,
			CG_RequestBossWarKickOut,
			CG_RequestBossWarReady,
			CG_RequestBossWarReturnReady,
			CG_RequestBossWarLeave,
			CG_RequestBossWarBattleStart,
			CG_RequestBossWarBattleSync,
			CG_RequestBossWarBattleEnd,
			CG_RequestBossWarReward,
			CG_RequestEventExchangeInfo,
			CG_RequestEventExchangeBoxGachaInfo,
			CG_RequestEventExchangeBoxGachaPickup,
			CG_RequestEventExchangeBoxGachaReset,
			CG_RequestEventPaybackReward,
			CG_RequestEventSnsShareProgress,
			CG_RequestEventSnsShareReward,
			CG_RequestGagueEventInfo,
			CG_RequestGagueEventCharge,
			CG_RequestGagueEventReward,
			CG_RequestGagueEventReset,
			CG_RequestEventLadderReward,
			CG_RequestEventLobbyGiftReward,
			CG_RequestEventTimeMissionInfo,
			CG_RequestEventTimeMissionStart,
			CG_RequestEventLobbyDecorationReward,
			CG_RequestRegistPlayTitle,
			CG_RequestPlayTitleMissionReward,
			CG_RequestTournamentList,
			CG_RequestTournamentProgressInfo,
			CG_RequestTournamentResultInfo,
			CG_RequestTournamentMatchJoin,
			CG_RequestTournamentMatchBattleStart,
			CG_RequestTournamentMatchBattleEnd,
			CG_RequestTournamentMatchExit,
			CG_RequestTournamentReward,
			CG_RequestTournamentPlayerTeamSlotChange,
			CG_RequestTournamentPlayerTeamInfo,
			CG_RequestTournamentCheer,
			CG_RequestTournamentCheerList,
			CG_RequestTournamentWatcherJoin,
			CG_RequestTournamentWatcherExit,
			CG_RequestTournamentMatchPlayInfo,
			CG_RequestTournamentReplayInfo,
			CG_RequestGuildWarLobbyInfo,
			CG_RequestGuildWarRankInfo,
			CG_RequestGuildWarVersusRecordInfo,
			CG_RequestGuildWarGuildMemberList,
			CG_RequestGuildWarWorldMapInfo,
			CG_RequestGuildWarAttackSquadChange,
			CG_RequestGuildWarDefenceTeamChange,
			CG_RequestGuildWarRegionBonusScoreChange,
			CG_RequestGuildWarAreaGuildMemberChange,
			CG_RequestGuildWarBattleRecordInfo,
			CG_Request_GuildWar_Stage_Start,
			CG_Request_GuildWar_Stage_Clear,
			CG_Request_GuildWar_Stage_Rejoin,
			CG_Request_GuildWar_Stage_HeroStatus_Sync,
		};
	}
}

				 
